shellcheck sanitized sh scripts

diff --git a/migratecfg/init-scripts/balena-common b/migratecfg/init-scripts/balena-common
--- a/migratecfg/init-scripts/balena-common
+++ b/migratecfg/init-scripts/balena-common
@@ -6,35 +6,38 @@
 ############################################################################
 
 checkMem() {
-	totMem=`cat /proc/meminfo | grep "MemTotal:"`
-	totMem=`expr match "$totMem" '[^:]\+:[^0-9]\+\([0-9]\+\)[^0-9]*kB'` || true
+	totMem=$(< /proc/meminfo grep "MemTotal:")
+	# shellcheck disable=SC2003
+	totMem=$(expr match "$totMem" '[^:]\+:[^0-9]\+\([0-9]\+\)[^0-9]*kB') || true
 	# totMem=`expr $totMem \* 1024` || true
 
 	log "total memory: ${totMem} kB"
 
-	freeMem=`cat /proc/meminfo | grep "MemFree:"` || true
-	freeMem=`expr match "$freeMem" '[^:]\+:[^0-9]\+\([0-9]\+\)[^0-9]*kB'` || true
+	freeMem=$(< /proc/meminfo grep "MemFree:") || true
+	# shellcheck disable=SC2003
+	freeMem=$(expr match "$freeMem" '[^:]\+:[^0-9]\+\([0-9]\+\)[^0-9]*kB') || true
 	# freeMem=`expr $freeMem \* 1024` || true
 	leftMem=$freeMem
 
 	log "free memory:  ${freeMem} kB"
-
+  # shellcheck disable=SC2154
 	if [ -f "${rootmnt}${HOME_DIR}/${IMAGE_FILE}" ] ; then
-	  tmp=`stat -c %s "${rootmnt}${HOME_DIR}/${IMAGE_FILE}"`
-		tmp=`expr $tmp / 1024` || true
+	  tmp=$(stat -c %s "${rootmnt}${HOME_DIR}/${IMAGE_FILE}")
+		tmp=$((tmp / 1024))
 		log "image file size: ${tmp} kB "
-	  leftMem=`expr $freeMem - $tmp`
+	  leftMem=$((freeMem - tmp))
 	fi
 
 	if [ -f "${rootmnt}${HOME_DIR}/${BACKUP_FILE}" ] ; then
-	  tmp=`stat -c %s "${rootmnt}${HOME_DIR}/${BACKUP_FILE}"`
-		tmp=`expr $tmp / 1024` || true
+	  tmp=$(stat -c %s "${rootmnt}${HOME_DIR}/${BACKUP_FILE}")
+		tmp=$((tmp / 1024))
 		log "backup file size: ${tmp} kB"
-	  leftMem=`expr $leftMem - $tmp`
+	  leftMem=$((leftMem - tmp))
 	fi
 
 	log "est. memory left after subtracting image & backup size: ${leftMem} kB "
 
+	# shellcheck disable=SC2086
 	if [ $leftMem -lt $MEM_MIN_FREE ] ; then
 		fail "not enough memory will be left after copying image & backup files, est.: ${leftMem} kB, currently free: ${freeMem} kB"
 	fi
@@ -59,15 +62,15 @@ logMsg() {
 log_to() {
 	NEW_LOG=$1
 
-	LOG_DIR=$(dirname $NEW_LOG)
-	if [ ! -d $LOG_DIR ] ; then
-		mkdir -p $LOG_DIR	|| fail  "failed to create log directory $LOG_DIR"
+	LOG_DIR=$(dirname "$NEW_LOG")
+	if [ ! -d "$LOG_DIR" ] ; then
+		mkdir -p "$LOG_DIR"	|| fail  "failed to create log directory $LOG_DIR"
 	fi
 
   if [ -n "$LOG_TO" ] && [ -f "$LOG_TO" ] ; then
     cp "$LOG_TO" "$NEW_LOG" || fail  "failed to copy log file $LOG_TO to $NEW_LOG"
 	else
-		touch $NEW_LOG ||  fail  "failed to create log file $NEW_LOG"
+		touch "$NEW_LOG" ||  fail  "failed to create log file $NEW_LOG"
   fi
 
   LOG_TO=$NEW_LOG
@@ -103,10 +106,11 @@ term() {
   fi
 
 	if [ -n "$UMOUNT_LOG" ] ; then
-		umount $UMOUNT_LOG || true
+		umount "$UMOUNT_LOG" || true
 	fi
 
-	if [ `echo ${FAIL_EXIT} | grep -c reboot ` -eq 1 ] ; then
+	# shellcheck disable=SC2086
+	if [ "$(echo \"${FAIL_EXIT}\" | grep -c reboot)" -eq 1 ] ; then
 		$FAIL_EXIT
   else
 		if [ -n "$TERM_EXIT" ] ; then
@@ -129,11 +133,11 @@ fail() {
   fi
 
 	if [ -n "$UMOUNT_BOOT" ] ; then
-		umount $UMOUNT_BOOT || true
+		umount "$UMOUNT_BOOT" || true
 	fi
 
 	if [ -n "$UMOUNT_LOG" ] ; then
-		umount $UMOUNT_LOG || true
+		umount "$UMOUNT_LOG" || true
 	fi
 
 	# TODO: umount some more
@@ -151,8 +155,8 @@ mount_device() {
 	MNT_FS_TYPE=$2
 	MNT_DIR=$3
 
-	if [ ! -d ${MNT_DIR} ] ; then
-	  mkdir -p ${MNT_DIR} || fail "failed to create mount dir ${MNT_DIR}"
+	if [ ! -d "${MNT_DIR}" ] ; then
+	  mkdir -p "${MNT_DIR}" || fail "failed to create mount dir ${MNT_DIR}"
 	fi
 
 	loopCount=0
@@ -161,11 +165,11 @@ mount_device() {
 		 log "log device not present: ${MNT_FS_NAME} waiting.."
 		 udevadm settle --timeout=5
 		 sleep 10
-		 loopCount=$(($loopCount + 1))
+		 loopCount=$((loopCount + 1))
 	done
 
 	if [ -b "${MNT_FS_NAME}" ] ; then
-		if ! mount -w -t ${MNT_FS_TYPE} ${MNT_FS_NAME} ${MNT_DIR} >>"$LOG_TO" 2>&1  ; then
+		if ! mount -w -t "${MNT_FS_TYPE}" "${MNT_FS_NAME}" "${MNT_DIR}" >>"$LOG_TO" 2>&1  ; then
 		  log "failed to mount device using  mount -w -t ${MNT_FS_TYPE} ${MNT_FS_NAME} ${MNT_DIR}"
 			return 1
 		else
diff --git a/migratecfg/init-scripts/balena-init b/migratecfg/init-scripts/balena-init
--- a/migratecfg/init-scripts/balena-init
+++ b/migratecfg/init-scripts/balena-init
@@ -17,9 +17,10 @@ esac
 # Begin real processing below this line
 
 copyPgm() {
-    local pgm="$1"
+		pgm="$1"
 
-    local pgmPath="$(whereis -b $pgm | awk '{ print $2}')"
+		# shellcheck disable=SC2086
+    pgmPath="$(whereis -b $pgm | awk '{ print $2}')"
 
     if [ -z "${pgmPath}" ] ; then
         echo "could not find ${pgmPath}"
@@ -27,7 +28,7 @@ copyPgm() {
 
     log "copy ${pgmPath}"
 
-    copy_exec ${pgmPath}
+    copy_exec "${pgmPath}"
 }
 
 log() {
@@ -56,7 +57,7 @@ fi
 
 for pgmName in ${REQUIRED_PGMS}
 do
-    copyPgm ${pgmName}
+    copyPgm "${pgmName}"
 done
 
 log "dest dir ${DESTDIR}"
@@ -83,7 +84,7 @@ log "copying network config files to initramfs"
 for file in $NETWORK_CONFIGS; do
 	if [ -f "${HOME_DIR}/$file" ] ; then
 		log "copying ${HOME_DIR}/$file"
-		cp "${HOME_DIR}/$file" "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/$fileto ${MIGRATE_DIR}/"
+		cp "${HOME_DIR}/$file" "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/$file to ${MIGRATE_DIR}/"
 	else
 		fail "could not find  ${HOME_DIR}/$file"
 	fi
@@ -92,7 +93,7 @@ done
 if [ -n "$GRUB_INSTALL" ] ; then
 	if [ -n "$GRUB_CFG" ] && [ -f "${HOME_DIR}/${GRUB_CFG}" ] ; then
 		log "copying ${HOME_DIR}/${GRUB_CFG}"
-		cp ${HOME_DIR}/${GRUB_CFG} "${MIGRATE_DIR}/grub.cfg" || fail "failed to copy ${HOME_DIR}/${GRUB_CFG}"
+		cp "${HOME_DIR}/${GRUB_CFG}" "${MIGRATE_DIR}/grub.cfg" || fail "failed to copy ${HOME_DIR}/${GRUB_CFG}"
 	else
 		fail "grub config not found in ${HOME_DIR}/${GRUB_CFG}"
 	fi
@@ -114,8 +115,8 @@ if [ -n "$GRUB_INSTALL" ] ; then
 	if [ "$GRUB_INSTALL" = "INSTALL" ] ; then
 		if [ -d /usr/lib/grub ] ; then
 			log "copy grub env from /usr/lib/grub"
-			mkdir -p ${DESTDIR}/usr/lib/grub
-			cp -r /usr/lib/grub/* ${DESTDIR}/usr/lib/grub || fail "failed to copy /usr/lib/grub"
+			mkdir -p "${DESTDIR}/usr/lib/grub"
+			cp -r /usr/lib/grub/* "${DESTDIR}/usr/lib/grub" || fail "failed to copy /usr/lib/grub"
 		else
 			log "/usr/lib/grub does not exist"
 			exit 1
diff --git a/migratecfg/init-scripts/balena-stage2-default b/migratecfg/init-scripts/balena-stage2-default
--- a/migratecfg/init-scripts/balena-stage2-default
+++ b/migratecfg/init-scripts/balena-stage2-default
@@ -16,6 +16,7 @@ esac
 set -e
 
 if [ -f /scripts/functions ] ; then
+		# shellcheck disable=SC1091
     . /scripts/functions
 fi
 
@@ -30,6 +31,7 @@ else
 fi
 
 if [ -f /scripts/balena-common ] ; then
+	# shellcheck source=/home/thomas/develop/balena.io/migrate/migratecfg/init-scripts/balena-common
     . /scripts/balena-common
 else
 		panic  "/scripts/balena-common not found"
@@ -42,7 +44,7 @@ fi
 #fi
 
 # Enable DEBUB output (debug function in balena-common)
-DEBUG_STAGE2=	#"TRUE"
+# DEBUG_STAGE2=	#"TRUE"
 # Set Failure exit to panic
 FAIL_EXIT="panic"
 # initialize log destination
@@ -70,9 +72,10 @@ fi
 if [ -n "$RESTORE_BOOT" ] ; then
 	log "attempting to restore boot configuration"
 
+	# shellcheck disable=SC2153
 	if [ "$MOUNT_BOOT" = "TRUE" ] ; then
 		# attempt to mount boot device
-		if ! mount_device ${ORIG_BOOT_PART} ${ORIG_BOOT_FS_TYPE} ${ORIG_BOOT_MNT} ; then
+		if ! mount_device ${ORIG_BOOT_PART} ${ORIG_BOOT_FS_TYPE} "${ORIG_BOOT_MNT}" ; then
 		 	log "failed to mount ${ORIG_BOOT_PART}"
 		else
 			UMOUNT_BOOT=${ORIG_BOOT_MNT}
@@ -83,7 +86,7 @@ if [ -n "$RESTORE_BOOT" ] ; then
 	sh -c "${RESTORE_BOOT}" >>"$LOG_TO" 2>&1 || fail "failed to restore boot configuration"
 
 	if [ -n "$UMOUNT_BOOT" ] ; then
-		umount ${UMOUNT_BOOT} >>"$LOG_TO" 2>&1 || fail "failed to unmount ${UMOUNT_BOOT}"
+		umount "${UMOUNT_BOOT}" >>"$LOG_TO" 2>&1 || fail "failed to unmount ${UMOUNT_BOOT}"
 		UMOUNT_BOOT=
 	fi
 
@@ -135,8 +138,9 @@ log "..done"
 # terminate if in NO_FLASH / test mode
 ######################################################################
 
-freeMem=`cat /proc/meminfo | grep "MemFree:"` || true
-freeMem=`expr match "$freeMem" '[^:]\+:[^0-9]\+\([0-9]\+\)[^0-9]*kB'` || true
+freeMem=$(< /proc/meminfo grep "MemFree:") || true
+# shellcheck disable=SC2003
+freeMem=$(expr match "$freeMem" '[^:]\+:[^0-9]\+\([0-9]\+\)[^0-9]*kB') || true
 log "Free memory after copy to initramfs: $freeMem kB"
 
 
@@ -153,7 +157,7 @@ fi
 ######################################################################
 
 log "unmounting root"
-umount ${rootmnt} || fail  "failed umount ${rootmnt}"
+umount "${rootmnt}" || fail  "failed umount ${rootmnt}"
 # TODO: remount as third exit ?
 FAIL_EXIT="reboot -f"
 log "..done"
