changes to grub setup recent images appear to contain a valid grub setup

diff --git a/migratecfg/init-scripts/balena-init b/migratecfg/init-scripts/balena-init
--- a/migratecfg/init-scripts/balena-init
+++ b/migratecfg/init-scripts/balena-init
@@ -89,16 +89,7 @@ for file in $NETWORK_CONFIGS; do
 	fi
 done
 
-if [ "$GRUB_INSTALL" = "INSTALL" ] ; then
-	if [ -d /usr/lib/grub ] ; then
-		log "copy grub env from /usr/lib/grub"
-		mkdir -p ${DESTDIR}/usr/lib/grub
-		cp -r /usr/lib/grub/* ${DESTDIR}/usr/lib/grub || fail "failed to copy /usr/lib/grub"
-	else
-		log "/usr/lib/grub does not exist"
-		exit 1
-	fi
-
+if [ -n "$GRUB_INSTALL" ] ; then
 	if [ -n "$GRUB_CFG" ] && [ -f "${HOME_DIR}/${GRUB_CFG}" ] ; then
 		log "copying ${HOME_DIR}/${GRUB_CFG}"
 		cp ${HOME_DIR}/${GRUB_CFG} "${MIGRATE_DIR}/grub.cfg" || fail "failed to copy ${HOME_DIR}/${GRUB_CFG}"
@@ -106,9 +97,34 @@ if [ "$GRUB_INSTALL" = "INSTALL" ] ; then
 		fail "grub config not found in ${HOME_DIR}/${GRUB_CFG}"
 	fi
 
-	if [ -f ${HOME_DIR}/device.map ] ; then
-		log "copying ${HOME_DIR}/device.map"
-		cp ${HOME_DIR}/device.map "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/device.map"
+	if [ "$GRUB_INSTALL" = "FLASH" ] ; then
+		if [ -n "$GRUB_BOOT_IMG" ] && [ -f "${HOME_DIR}/${GRUB_BOOT_IMG}" ] ; then
+			cp "${HOME_DIR}/${GRUB_BOOT_IMG}" "${MIGRATE_DIR}/boot.img" || fail "failed to copy ${HOME_DIR}/${GRUB_BOOT_IMG} to ${MIGRATE_DIR}/boot.img"
+		else
+			fail "grub boot image not set or not found in ${HOME_DIR}/${GRUB_BOOT_IMG}"
+		fi
+
+		if [ -n "$GRUB_CORE_IMG" ] && [ -f "${HOME_DIR}/${GRUB_CORE_IMG}" ] ; then
+			cp "${HOME_DIR}/${GRUB_CORE_IMG}" "${MIGRATE_DIR}/core.img" || fail "failed to copy ${HOME_DIR}/${GRUB_CORE_IMG} to ${MIGRATE_DIR}/core.img"
+		else
+			fail "grub core image not set or not found in ${HOME_DIR}/${GRUB_CORE_IMG}"
+		fi
+	fi
+
+	if [ "$GRUB_INSTALL" = "INSTALL" ] ; then
+		if [ -d /usr/lib/grub ] ; then
+			log "copy grub env from /usr/lib/grub"
+			mkdir -p ${DESTDIR}/usr/lib/grub
+			cp -r /usr/lib/grub/* ${DESTDIR}/usr/lib/grub || fail "failed to copy /usr/lib/grub"
+		else
+			log "/usr/lib/grub does not exist"
+			exit 1
+		fi
+
+		if [ -f ${HOME_DIR}/device.map ] ; then
+			log "copying ${HOME_DIR}/device.map"
+			cp ${HOME_DIR}/device.map "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/device.map"
+		fi
 	fi
 fi
 
diff --git a/migratecfg/init-scripts/balena-stage2-default b/migratecfg/init-scripts/balena-stage2-default
--- a/migratecfg/init-scripts/balena-stage2-default
+++ b/migratecfg/init-scripts/balena-stage2-default
@@ -218,7 +218,9 @@ fi
 #fi
 
 
-if [ -n "$GRUB_INSTALL"] ; then
+if [ -n "$GRUB_INSTALL" ] ; then
+	log "setting up grub boot config: GRUB_INSTALL = $GRUB_INSTALL"
+
 	if [ -f ${MIGRATE_TMP}/grub.cfg ] ; then
 		log "copying grub.cfg"
 		mkdir -p ${BOOT_MNT_DIR}/grub >>$LOG_TO 2>&1 || fail "failed to create directory ${BOOT_MNT_DIR}/grub"
@@ -229,16 +231,16 @@ if [ -n "$GRUB_INSTALL"] ; then
 
 	if [ "$GRUB_INSTALL" = "FLASH" ] ; then
 		if [ -f "${MIGRATE_TMP}/boot.img" ] && [ -f "${MIGRATE_TMP}/core.img" ] ; then
+			log "flashing boot.img / core.img to boot device"
 			# install grub img files
 			if [ -d "${BOOT_MNT_DIR}/EFI" ]  ; then
 				log "deleting ${BOOT_MNT_DIR}/EFI"
 				rm -rf ${BOOT_MNT_DIR}/EFI >>"$LOG_TO" 2>&1 || log "failed to delete ${BOOT_MNT_DIR}/EFI"
 			fi
-			dd if="${MIGRATE_TMP}/boot.img" of=dd of=${BOOT_DEV} conv=fdatasync bs=1M >>"$LOG_TO" 2>&1 || log "failed to flash ${MIGRATE_TMP}/boot.img"
-			dd if="${MIGRATE_TMP}/core.img" of=${BOOT_DEV} conv=fdatasync bs=512 seek=1	>>"$LOG_TO" 2>&1 || log "failed to flash ${MIGRATE_TMP}/core.img"
+			dd if="${MIGRATE_TMP}/boot.img" of=dd of=${BOOT_DEV} conv=fdatasync bs=1M >>"$LOG_TO" 2>&1 || fail "failed to flash ${MIGRATE_TMP}/boot.img"
+			dd if="${MIGRATE_TMP}/core.img" of=${BOOT_DEV} conv=fdatasync bs=512 seek=1	>>"$LOG_TO" 2>&1 || fail "failed to flash ${MIGRATE_TMP}/core.img"
 		else
-			log "warning: grub images not found, falling back to grub-install"
-			GRUB_INSTALL="INSTALL"
+			fail "grub images not found, falling back to grub-install"
 		fi
 	fi
 
@@ -290,6 +292,8 @@ if [ -n "$GRUB_INSTALL"] ; then
 	#									${BOOT_DEV} >>"$LOG_TO" 2>&1 || fail "failed to install grub"
 		fi
 	fi
+else
+	log "not a grub install"
 fi
 
 ######################################################################
