wip on x86 migration

diff --git a/scripts/raspi/balena-stage1 b/scripts/raspi/balena-stage1
--- a/scripts/raspi/balena-stage1
+++ b/scripts/raspi/balena-stage1
@@ -14,8 +14,8 @@ HOME_DIR=./
 # reboot automatically after script has finished by setting to "TRUE"
 DO_REBOOT= # "TRUE"
 # name of the balenaOS image to flash (expected in $HOMEDIR)
-IMAGE_NAME="resin-image-genericx86-64.resinos-img.gz"
-# IMAGE_NAME="resin-resintest-raspberrypi3-2.15.1+rev2-dev-v7.16.6.img.gz"
+# IMAGE_NAME="resin-image-genericx86-64.resinos-img.gz"
+IMAGE_NAME="resin-resintest-raspberrypi3-2.15.1+rev2-dev-v7.16.6.img.gz"
 
 # switch on initramfs / kernel debug mode by seting to "TRUE"
 DEBUG="TRUE"
@@ -31,7 +31,7 @@ GRUB_BOOT_DEV="hd0,msdos1"
 GRUB_BOOT_TYPE="legacy"
 
 # DEBUG end initramfs scripts before unmounting root / flashing the image
-NO_FLASH="TRUE"
+NO_FLASH= #"TRUE"
 ERROR_EXIT= # "reboot -f"
 
 # DEBUG: do not modify config.txt if set to "TRUE"
@@ -44,11 +44,9 @@ INITRAMFS_NAME="balena-migrate-initramfs-$(uname -r)"
 MK_INITRAM_VERBOSE= # "TRUE"
 # DEBUG keep initramfs layout
 MK_INITRAM_RETAIN= # "TRUE"
-# script namme for logging
-SCRIPT_NAME="balena-stage1"
 
 # attempt to mount and log initramfs logs to external drive if set
-LOG_DRIVE=/dev/sdb1
+LOG_DRIVE=/dev/sda1
 LOG_FS_TYPE=ext4
 
 HAS_WIFI_CFG="FALSE" # set to "TRUE" if a wifi config is provided in image
@@ -72,6 +70,8 @@ RASPI_3_REVS="a02082 a020a0 a22082 a32082 a020d3"
 
 GRUB_MIN_VER=2
 BOOT_DIR=/boot
+# script namme for logging
+SCRIPT_NAME="balena-stage1"
 
 
 ##########################################
@@ -367,15 +367,20 @@ function checkArmDevs {
 ####################################################
 
 function setupBootCfg_rpi {
-
+  inform "setupBootCfg_rpi"
   ##########################
   ## Modify /boot/config.txt
   ##########################
 
+  INITRAM_REQUIRED_PGMS="${INITRAM_REQUIRED_PGMS} cp cat rm sleep"
   inform "making backup of config.txt"
   CONFIG_TXT_BACKUP="${CONFIG_TXT}.$(date +%Y%m%d-%H-%M-%S)"
   TMP_FILE=$(mktemp)
   INITRAM_CMD="initramfs ${INITRAMFS_NAME} followkernel"
+
+  # make sure BUSYBOX is NOT used
+  inform "checking initramfs-tools config"
+  sed -i 's/^\(BUSYBOX\s*=\s*\).*$/\1n/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
 
   while read -r line
   do
@@ -411,8 +416,6 @@ function setupBootCfg_rpi {
     fi
   fi
 
-  inform "copying ${HOME_DIR}/${INITRAMFS_NAME} to ${BOOT_DIR}/"
-  cp ${HOME_DIR}/${INITRAMFS_NAME} "${BOOT_DIR}/" || fail "failed to copy ${HOME_DIR}/${INITRAMFS_NAME} to ${BOOT_DIR}/"
 }
 
 ####################################################
@@ -420,11 +423,24 @@ function setupBootCfg_rpi {
 ####################################################
 
 function setupBootCfg_other {
+  inform "setupBootCfg_other"
   # TODO: grub boot device is set in $GRUB_BOOT_DEV - try to determine it from setup (eg. grub.conf)
   # TODO: assuming we are on debian like OS
 
   # BOOT_IMAGE=/boot/vmlinuz-4.4.0-31-generic root=UUID=1bddfe9b-69cd-499d-bd21-2639700a899e ro
-  INITRAM_REQUIRED_PGMS="${INITRAM_REQUIRED_PGMS} grub-install"
+
+  # TODO: this is ublikely to work but I will try it
+  INITRAM_REQUIRED_PGMS="${INITRAM_REQUIRED_PGMS} grub-install busybox"
+
+  # make sure BUSYBOX is used
+  inform "checking initramfs-tools config"
+  sed -i 's/^\(BUSYBOX\s*=\s*\).*$/\1y/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
+
+  local efiBootMgr=$(whereis -b efibootmgr | awk '{ print $2}')
+  if [ -n "$efiBootMgr" ] &&  efibootmgr &>/dev/null ; then
+    GRUB_BOOT_TYPE="UEFI"
+    INITRAM_REQUIRED_PGMS="${INITRAM_REQUIRED_PGMS} efibootmgr"
+  fi
 
   local KERNEL_CMD_LINE_RAW=$(cat /proc/cmdline)
   if [ -z "$KERNEL_CMD_LINE_RAW" ] ; then
@@ -488,24 +504,21 @@ function setupBootCfg_other {
     KBOOT_DIR="${KBOOT_DIR}/"
   fi
 
-  inform "copying ${HOME_DIR}/${INITRAMFS_NAME} to ${BOOT_DIR}"
-  cp ${HOME_DIR}/${INITRAMFS_NAME} "${BOOT_DIR}" || fail "failed to copy ${HOME_DIR}/${INITRAMFS_NAME} to ${BOOT_DIR}"
-
   if [ -z "$(whereis -b update-grub)" ] || [ -z "$(whereis -b grub-reboot)" ] ; then
-      fail "failed to ensure required programs update-grub, grub-reboot, grub-install"
+      fail "failed to ensure required programs update-grub, grub-reboot"
   fi
 
   if [ ! -d /etc/grub.d ] ; then
       fail "grub configuration not found"
   fi
 
-TODO: make grub HD num from hdDev, just assuming 0 for now
+# TODO: make grub HD num from hdDev, just assuming 0 for now
 
-GRUB_INSTALL="TRUE"
-local grubDev=$(expr match "$GRUB_BOOT_DEV" '^\([^,]\+\),.*')
-echo "(${grubDev}) $ROOT_DEV" > ${HOME_DIR}/device.map
+  GRUB_INSTALL="TRUE"
+  local grubDev=$(expr match "$GRUB_BOOT_DEV" '^\([^,]\+\),.*')
+  echo "(${grubDev}) $ROOT_DEV" > ${HOME_DIR}/device.map
 
-cat << EOI > ${HOME_DIR}/grub.cfg
+  cat << EOI > ${HOME_DIR}/grub.cfg
 serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1
 default=boot
 timeout=0
@@ -533,15 +546,17 @@ menuentry "resin-migration" {
 EOI
 chmod +x /etc/grub.d/42_resin
 
-inform "updating grub config using ${GRUBUPDT}"
-update-grub || fail "failed to update grub config"
-inform "calling grub-reboot resin-migration"
-grub-reboot resin-migration
+  inform "updating grub config using ${GRUBUPDT}"
+  update-grub || fail "failed to update grub config"
+  inform "calling grub-reboot resin-migration"
+  grub-reboot resin-migration
 }
 
-##########################################
+####################################################################################
+####################################################################################
 # main : create initramfs & install it
-##########################################
+####################################################################################
+####################################################################################
 
 if [[ $EUID -ne 0 ]]; then
     fail "This script must be run as root"
@@ -551,17 +566,9 @@ inform "establishing required programs"
 
 # TODO: Check / install tools needed for initramfs too
 
-INITRAM_REQUIRED_PGMS="mkdir dd gzip df parted echo reboot partprobe sync dirname lsblk"
+INITRAM_REQUIRED_PGMS="mkdir dd gzip df parted echo reboot partprobe sync dirname lsblk udevadm"
 REQUIRED_PGMS="lsblk readlink mkinitramfs sed" #  gzip
 checkPgms $REQUIRED_PGMS
-
-for PGM in $REQUIRED_PGMS
-do
-    PGM_PATH="$(whereis -b $PGM | awk '{ print $2}')"
-    if [ -z "$PGM_PATH" ] || [ ! -f "$PGM_PATH" ] ; then
-      fail "cannot find required program: $PGM as $PGM_PATH"
-   fi
-done
 
 inform "checked required programs"
 
@@ -636,6 +643,25 @@ ROOT_DEV=${TMP[0]}/${TMP[1]}
 inform "ROOT_DEV=${ROOT_DEV}"
 
 ###########################
+## create boot configuration
+###########################
+
+if [ ! "$NO_SETUP" == "TRUE" ] ; then
+  inform "boot setup enabled: NO_SETUP=$NO_SETUP"
+  if [ "$IS_PI" == "TRUE" ] ; then
+    inform "performing boot setup for RPI: $IS_PI"
+    setupBootCfg_rpi
+  else
+    inform "performing boot setup for other: $IS_PI"
+    setupBootCfg_other
+  fi
+else
+  inform "boot setup disabled: NO_SETUP=$NO_SETUP"
+fi
+
+
+
+###########################
 ## write /etc/migrate.conf
 ###########################
 
@@ -669,6 +695,8 @@ NO_FLASH=${NO_FLASH}
 ERROR_EXIT=${ERROR_EXIT}
 
 GRUB_INSTALL=${GRUB_INSTALL}
+GRUB_BOOT_TYPE=${GRUB_BOOT_TYPE}
+
 EOI
 
 #####################################
@@ -738,22 +766,8 @@ if [ "${MK_INITRAMFS}" == TRUE ] ; then
     inform "creating initramfs: mkinitramfs $OPTS"
     mkinitramfs $OPTS || fail "failed to create initramfs in ${HOME_DIR}/${INITRAMFS_NAME}"
 
-    # inform "copying initramfs"
-    # cp ${HOME_DIR}/${INITRAMFS_NAME} /boot || fail "failed to copy ${HOME_DIR}/${INITRAMFS_NAME} to /boot"
-fi
-
-
-if [ ! "$NO_SETUP" == "TRUE" ] ; then
-  inform "boot setup enabled: NO_SETUP=$NO_SETUP"
-  if [ "$IS_PI" == "TRUE" ] ; then
-    inform "performing boot setup for RPI: $IS_PI"
-    setupBootCfg_rpi
-  else
-    inform "performing boot setup for other: $IS_PI"
-    setupBootCfg_other
-  fi
-else
-  inform "boot setup disabled: NO_SETUP=$NO_SETUP"
+    inform "copying ${HOME_DIR}/${INITRAMFS_NAME} to ${BOOT_DIR}/"
+    cp ${HOME_DIR}/${INITRAMFS_NAME} "${BOOT_DIR}/" || fail "failed to copy ${HOME_DIR}/${INITRAMFS_NAME} to ${BOOT_DIR}/"
 fi
 
 ###########################
diff --git a/scripts/raspi/initramfs-tools/scripts/local-bottom/balena-stage2-default b/scripts/raspi/initramfs-tools/scripts/local-bottom/balena-stage2-default
--- a/scripts/raspi/initramfs-tools/scripts/local-bottom/balena-stage2-default
+++ b/scripts/raspi/initramfs-tools/scripts/local-bottom/balena-stage2-default
@@ -53,9 +53,19 @@ log "local-bottom balena-stage2-default started"
 
 
 if [ -n "$LOG_DRIVE" ] ; then
+	# TODO: needs to wait for USB drive to show up
 	mkdir -p ${LOG_MOUNT_DIR} || fail "failed to create mount dir ${LOG_MOUNT_DIR}"
-	/bin/mount -w -t ${LOG_FS_TYPE} ${LOG_DRIVE} ${LOG_MOUNT_DIR} || fail "failed to mount log dir using /bin/mount -w -t ${LOG_FS_TYPE} ${LOG_DRIVE} ${LOG_MOUNT_DIR}"
+	loopCount=0
+	while [ ! -b "$LOG_DRIVE" ] && [ $loopCount -lt 3 ] ;
+	do
+	   log "log device not present: $LOG_DRIVE waiting.."
+	   udevadm settle --timeout=10
+	   sleep 10
+	   loopCount=$(($loopCount + 1))
+	done
+	mount -w -t ${LOG_FS_TYPE} ${LOG_DRIVE} ${LOG_MOUNT_DIR} || fail "failed to mount log dir using mount -w -t ${LOG_FS_TYPE} ${LOG_DRIVE} ${LOG_MOUNT_DIR}"
 	log_to "${LOG_MOUNT_DIR}/${LOG_FILE}"
+	log "logging to ${LOG_MOUNT_DIR}/${LOG_FILE}"
 fi
 
 log "creating migrate dir ${MIGRATE_TMP}"
@@ -139,6 +149,7 @@ if [ -f "${MIGRATE_TMP}/${BACKUP_FILE}" ] ; then
 	log "...done"
 fi
 
+
 log "mounting resin-boot using: mount -w -t $BOOT_PART_TYPE $BOOT_PART_NAME $BOOT_MNT_DIR"
 mount -w -t $BOOT_PART_TYPE $BOOT_PART_NAME "$BOOT_MNT_DIR" >>"$LOG_TO" 2>&1 || fail  "failed to mount resin-boot partition"
 log "..done"
@@ -150,6 +161,29 @@ for file in $NETWORK_CONFIGS; do
 	cp "${MIGRATE_TMP}/$file" "${BOOT_MNT_DIR}/system-connections/$file" >>"$LOG_TO" 2>&1  || log "no network config copied"
 done
 log "..done"
+
+if [ "$GRUB_INSTALL" = "TRUE" ] ; then
+	log "attempting grub install with type $GRUB_BOOT_TYPE"
+	if [ -f ${MIGRATE_TMP}/grub.cfg ] ; then
+		cp ${MIGRATE_TMP}/grub.cfg ${BOOT_MNT_DIR}/grub/ || fail "failed to copy ${MIGRATE_TMP}/grub.cfg"
+	fi
+
+	if [ "$GRUB_BOOT_TYPE" = "legacy" ] ; then
+	# if [ "${FLASH_BOOTLOADER}" == "TRUE" ] ; then
+	# 		inform "flashing boot.img os to ${ORIG_BOOT_DEV}"
+	# 		dd if=${BOOT_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1
+	# 		inform "flashing core.img os to ${ORIG_BOOT_DEV}"
+	# 		dd if=${CORE_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1 seek=512
+	# fi
+
+#--modules="biosdisk part_msdos ext2 configfile normal multiboot" \
+
+		grub-install 	--no-floppy \
+									--grub-mkdevicemap=${MIGRATE_TMP}/device.map \
+									--boot-directory=${BOOT_MNT_DIR} \
+									${ROOT_DEV} >>"$LOG_TO" 2>&1 || fail "failed to install grub"
+	fi
+fi
 
 # saveLog || true
 sync || true
