added logging

diff --git a/util/migdb-migrate b/util/migdb-migrate
--- a/util/migdb-migrate
+++ b/util/migdb-migrate
@@ -389,22 +389,25 @@ function process {
   successMsg=$(echo "$tmpStr" | grep -E "\[[^\]+\]*.INFO:.*migration successful,")
 
   if [ $? -eq 0 ] && [ -n "$successMsg" ] ; then    
-      if [[ "$successMsg" =~ .*please\ reboot\ system.* ]] ; then
-        if ! "$sshCmd \"sudo reboot\"" ; then
-          unitFailed "$UNIT_ID" "$UNIT_FILE" "failed reboot on ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT}"
-          return 0
-        fi
+    inform "unit id ${UNIT_ID}, successfully migrated"
+
+    if [[ $successMsg =~ .*please\ reboot\ system.* ]] ; then
+      inform "unit id ${UNIT_ID}, rebooting device"
+      if ! "$sshCmd \"sudo reboot\"" ; then
+        unitFailed "$UNIT_ID" "$UNIT_FILE" "failed reboot on ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT}"
+        return 0
       fi
+    fi
 
-      now=$(date +%s)
-      setVar "STATUS_TS" "$now" "$UNIT_FILE"
-      setVar "DUE_TS" "$((now + MIG_DURATION))" "$UNIT_FILE"
-      setVar "STATUS" "MIGRATED" "${UNIT_FILE}" || fail "failed to update status on ${UNIT_FILE}"
+    now=$(date +%s)
+    setVar "STATUS_TS" "$now" "$UNIT_FILE"
+    setVar "DUE_TS" "$((now + MIG_DURATION))" "$UNIT_FILE"
+    setVar "STATUS" "MIGRATED" "${UNIT_FILE}" || fail "failed to update status on ${UNIT_FILE}"
 
-      moveFile "${UNIT_FILE}" "${PROCESS_DIR}" "${UNIT_ID}" || fail "failed to move ${UNIT_FILE} to ${PROCESS_DIR}, ${UNIT_ID}"
+    moveFile "${UNIT_FILE}" "${PROCESS_DIR}" "${UNIT_ID}" || fail "failed to move ${UNIT_FILE} to ${PROCESS_DIR}, ${UNIT_ID}"
   else
-      unitFailed "$UNIT_ID" "$UNIT_FILE" "cannot find success message in migrate log from ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT}"
-      return 0
+    unitFailed "$UNIT_ID" "$UNIT_FILE" "cannot find success message in migrate log from ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT}"
+    return 0
   fi
 
   sleep 3
