minor changes from sonder debugging

diff --git a/util/migdb-common b/util/migdb-common
--- a/util/migdb-common
+++ b/util/migdb-common
@@ -179,7 +179,7 @@ function orderFailed {
   now=$(date +%s)
   failFile=$(mktemp -p "${FAIL_DIR}" "fail-$orderId-XXX")
   mv "$orderFile" "$failFile"
-  echo "FAILT_TS=$now" >> "${failFile}" || fail "failed to create fail file for order $orderId in $failFile"
+  echo "FAIL_TS=$now" >> "${failFile}" || fail "failed to create fail file for order $orderId in $failFile"
   echo "FAIL_MSG=\"$msg\"" >> "${failFile}" || fail "failed to create fail file for order $orderId in $failFile"
   echo "FAIL_LOG=\"$OUTPUT_LOG\"" >> "${failFile}" || fail "failed to create fail file for order $orderId in $failFile"
   OUTPUT_LOG=
