debug reconnect & cleanup of logs

diff --git a/util/migdb-add-unit b/util/migdb-add-unit
--- a/util/migdb-add-unit
+++ b/util/migdb-add-unit
@@ -1,20 +1,15 @@
 #!/bin/bash
 
 SCRIPT_PATH=$(dirname "${0}")
-# shellcheck source=/home/thomas/develop/balena.io/migrate/util/migdb-common
+# shellcheck source=migdb-common
 source "${SCRIPT_PATH}/migdb-common"
 
 color ON
 
-if [ -z "$MIG_DB_DIR" ] ; then
-  MIG_DB_DIR=.
-fi
+MIG_DB_DIR=${MIG_DB_DIR=${PWD}}
 
-#shellcheck disable=SC2034
-DEBUG_FUNCTS="main checkInit"
-#shellcheck disable=SC2034
-LOG_DEBUG="TRUE"
-#shellcheck disable=SC2034
+DEBUG_FUNCTS="main checkInit moveFile"
+LOG_DEBUG= # ""
 SCRIPT_NAME="migdb-add-unit"
 
 function printHelp {
@@ -23,7 +18,7 @@ function printHelp {
   USAGE: migdb-add-unit [options] <unitId>
   options are:
     --app <balena-application>     - Unit specific balena application to register with
-    --base <db base dir>           - Base directory of order db
+    --base <db base dir>           - Base directory of unit db
     --cfg <migrate-config-file>    - Unit specific config variables in bash / sh format
     --cfg-dir <migratecfg dir>     - Unit specific migrate config directory
     --cfg-tgz <migratecfg archive> - Unit specific gzipped tar archive of migratecfg directory
@@ -163,7 +158,7 @@ function getCmdArgs {
   done
 }
 
-# debug main "base dir is: $MIG_DB_DIR, orders dir is: $ORDERS"
+# debug main "base dir is: $MIG_DB_DIR, units dir is: $ORDERS"
 
 getCmdArgs "$@"
 
@@ -178,7 +173,7 @@ checkInit
 for file in ${UNIT_DIR}/* ; do
   # echo "got $file"
   if [[ $file =~ ^${UNIT_DIR}/unit-${UNIT_ID}-.* ]] ; then 
-    echo "an order file for order $UNIT_ID exists: ${UNIT_DIR}/${file}"
+    fail "a unit file for unit id $UNIT_ID exists: ${file}"
   fi
 done
 
@@ -190,7 +185,7 @@ if [ $EUID -eq 0 ]; then
   chmod 777 "${TMP_FILE}"
 fi
 
-cat <<EOI > "${TMP_FILE}"  || fail "failed to create order file for orderid $UNIT_ID"
+cat <<EOI > "${TMP_FILE}"  || fail "failed to create unit file for unitid $UNIT_ID"
 UNIT_ID=${UNIT_ID}
 STATUS=INIT
 CREATE_TS=$(date +%s)
@@ -234,12 +229,14 @@ EOI
   fi
 }  >> "${TMP_FILE}"
 
-if moveFile "$TMP_FILE" "${UNIT_DIR}" "${UNIT_ID}" ; then
-  inform "order file created for order id ${UNIT_ID},  port $MIG_SSH_PORT in ${UNIT_FILE}"
+debug main "${TMP_FILE} contents:"
+
+if moveFile "${TMP_FILE}" "${UNIT_DIR}" "${UNIT_ID}" ; then
+  inform "a unit file was created for unit id ${UNIT_ID}"
 
   #if ! ps -av | grep migdb-process ; then
   #   inform "it appears that the migdb-process script is not running, please run the script to process your unit files"
   #fi
 else
-  fail "failed to create order file for order ${UNIT_ID} in ${UNIT_DIR}"
+  fail "failed to create unit file for unit ${UNIT_ID} in ${UNIT_DIR}"
 fi
diff --git a/util/migdb-check-done b/util/migdb-check-done
--- a/util/migdb-check-done
+++ b/util/migdb-check-done
@@ -1,24 +1,17 @@
 #!/bin/bash
 
-if [ -z "$MIG_DB_DIR" ] ; then
-  MIG_DB_DIR=.
-fi
+MIG_DB_DIR=${MIG_DB_DIR=${PWD}}
 
 COLOR=ON
-#shellcheck disable=SC2034
 DEBUG_FUNCTS="process"
-#shellcheck disable=SC2034
 LOG_DEBUG=FALSE
-
-#shellcheck disable=SC2034
 SCRIPT_NAME="migdb-check-done"
 SLEEP_DURATION=5
-
 SCRIPT_PATH=$(dirname "${0}")
 
 
 if [ -f "${SCRIPT_PATH}/migdb-common" ] ; then
-  #shellcheck source=./migdb-common
+  #shellcheck source=migdb-common
   source "${SCRIPT_PATH}/migdb-common"
 else
   fail "could not find ${SCRIPT_PATH}/migdb-common"  
@@ -125,7 +118,7 @@ function process {
 
   if [ -z "$STATUS" ] && [ "$STATUS" != "MIGRATED" ] ; then
     # shellcheck disable=SC2153
-    orderFailed "$UNIT_ID" "$UNIT_FILE" "invalid status found in unit file $UNIT_FILE"
+    unitFailed "$UNIT_ID" "$UNIT_FILE" "invalid status found in unit file $UNIT_FILE"
     return 0
   fi
 
@@ -148,12 +141,12 @@ function process {
         DEVICE_ONLINE=TRUE
         now=$(date +%s)
 
-        setvar "STATUS_TS" "${now}" "${UNIT_FILE}"
-        setvar "MIGRATE_S2_LOG" "${OUTPUT_LOG}" "${UNIT_FILE}"
-        setvar "STATUS" "DONE" "${UNIT_FILE}" || fail "failed to update status on ${UNIT_FILE}"
+        setVar "STATUS_TS" "${now}" "${UNIT_FILE}"
+        setVar "MIGRATE_S2_LOG" "${OUTPUT_LOG}" "${UNIT_FILE}"
+        setVar "STATUS" "DONE" "${UNIT_FILE}" || fail "failed to update status on ${UNIT_FILE}"
         OUTPUT_LOG=
 
-        inform "success: device was found online, unit: ${UNIT_ID}, uuid: ${DEVICE_ID}"
+        inform "success: device was found online, unit id: ${UNIT_ID}, uuid: ${DEVICE_ID}"
         moveFile "${UNIT_FILE}" "${DONE_DIR}" "${UNIT_ID}" || fail "failed to move ${UNIT_FILE} to ${DONE_DIR}, ${UNIT_ID}"
         break;
       fi
@@ -164,7 +157,7 @@ function process {
 
       statusAge=$((now - STATUS_TS))
       if [ $statusAge -gt "$MIG_MAX_STATUS_AGE" ] ; then
-        orderFailed "$UNIT_ID" "$UNIT_FILE" "Device has not shown up after $statusAge sconds"
+        unitFailed "$UNIT_ID" "$UNIT_FILE" "Device has not shown up after $statusAge sconds"
         return 0
       fi
 
@@ -175,7 +168,7 @@ function process {
       OUTPUT_LOG=
     fi
   else
-    orderFailed "$UNIT_ID" "$UNIT_FILE" "failed to retrieve device information from balena"  	
+    unitFailed "$UNIT_ID" "$UNIT_FILE" "failed to retrieve device information from balena"  	
   fi
 
   return 0
diff --git a/util/migdb-common b/util/migdb-common
--- a/util/migdb-common
+++ b/util/migdb-common
@@ -52,6 +52,14 @@ function warn {
 }
 
 ##########################################
+# error : print error message
+##########################################
+
+function error {
+  printf "${RED}[%s %s %s ERROR]:${NC} %s \n" "$(date +%T)" "${SCRIPT_NAME}" "$$" "$1"
+}
+
+##########################################
 # fail : print failurwe message and exit
 ##########################################
 
@@ -96,7 +104,7 @@ function checkInit {
 
   if [ ! -d "$MIG_DB_DIR" ] || [ ! -d "$UNIT_DIR" ] || [ ! -d "$FAIL_DIR" ] || [ ! -d "$DONE_DIR" ] || [ ! -d "$TMP_DIR" ] ; then
       inform "initializing directory structure in $MIG_DB_DIR"
-      mkdir -p "$UNIT_DIR" || fail "failed to create orders directory in $UNIT_DIR"
+      mkdir -p "$UNIT_DIR" || fail "failed to create unit directory in $UNIT_DIR"
       mkdir -p "$PROCESS_DIR" || fail "failed to create process directory in $PROCESS_DIR"
       mkdir -p "$DONE_DIR" || fail "failed to create done directory in $DONE_DIR"
       mkdir -p "$FAIL_DIR" || fail "failed to create fail directory in $FAIL_DIR"
@@ -138,18 +146,14 @@ function moveFile {
   local id=$3  
   local target
   
+  debug moveFile "src=${src} dir=${dir} id=${id}"
+
   target=$(mktemp -p "${dir}" "unit-${id}-XXX") 
 
-  if mv -n "${src}" "${target}" ; then
-    if [ ! -f  "${src}" ] ; then
-      return 0
-    else
-      target=$(mktemp -p "${FAIL_DIR}" "move-fail-${id}-XXX")
-      mv "${src}" "$target"
-      return 1
-    fi
-  else
-    return 2
+  if mv -f "${src}" "${target}" ; then
+    return 0
+  else 
+    return 1
   fi
 }
 
@@ -193,21 +197,21 @@ function getRandFile {
 
 
 ################################################################################
-# copy / append failed order file to fail dir
+# copy / append failed unit file to fail dir
 ################################################################################
 
-function orderFailed {
-  local orderId=$1
-  local orderFile=$2
+function unitFailed {
+  local unitId=$1
+  local unitFile=$2
   local msg=$3
   local now failFile
-  warn "ORDER ${orderId}: $msg"
+  error "unit id ${unitId}: $msg"
   now=$(date +%s)
-  failFile=$(mktemp -p "${FAIL_DIR}" "fail-$orderId-XXX")
-  mv "$orderFile" "$failFile"
+  failFile=$(mktemp -p "${FAIL_DIR}" "fail-${unitId}-XXX")
+  mv "$unitFile" "$failFile"
   setVar  "FAIL_TS" "${now}" "${failFile}"
   setVar  "FAIL_MSG" "$msg" "${failFile}"
-  setVar  "FAIL_LOG" "$OUTPUT_LOG" "${failFile}" || fail "failed to create fail file for order $orderId in $failFile"
+  setVar  "FAIL_LOG" "$OUTPUT_LOG" "${failFile}" || fail "failed to create fail file for unit id ${unitId} in ${failFile}"
   OUTPUT_LOG=
 }
 
