changes to unit and logfiles and to migdb-stats

diff --git a/util/migdb-migrate b/util/migdb-migrate
--- a/util/migdb-migrate
+++ b/util/migdb-migrate
@@ -13,7 +13,7 @@ MIG_RECONN_TIME=${MIG_RECONN_TIME=600}
 TGT_DIR="migrate"
 COLOR=ON
 
-DEBUG_FUNCTS="process sendDir sendFile sendTgzFile execSshCmd"
+DEBUG_FUNCTS="process setStrVar"
 LOG_DEBUG=FALSE
 SCRIPT_NAME=$(basename "${0}")
 SCRIPT_PATH=$(dirname "${0}")
@@ -228,6 +228,7 @@ function getCmdArgs {
 function process {
   debug process "with $UNIT_FILE"
 
+  MIG_SSH_PORT=
   MIG_SSH_OPTS=
   MIG_CONN_RETRIES=0
   DUE_TS=
@@ -299,36 +300,69 @@ function process {
     timeTillNext=86400
   fi
 
+  local connFailed wcOut lineCount
+  
+  wcOut=($(wc -l "${UNIT_OUTPUT_LOG}"))
+  debug process "lineCount: ${wcOut[0]}"
+  # shellcheck disable=SC2178
+  lineCount=$((wcOut[0]+2))
+
   if [ -n "$MIG_CFG_ARCHIVE" ] && [ -f "$MIG_CFG_ARCHIVE" ] ; then
     if ! sendTgzFile "$MIG_CFG_ARCHIVE" "$TGT_DIR" "$MIG_TX_TIMEOUT" ; then
+      connFailed=TRUE
+    fi
+  else
+    if [ -n "$MIG_CFG_DIR" ] && [ -d "$MIG_CFG_DIR" ] ; then      
+      if ! sendDir "$MIG_CFG_DIR" "$TGT_DIR" "$MIG_TX_TIMEOUT" ; then        
+        connFailed=TRUE
+      fi
+    fi
+  fi
+
+  if [ -n "$connFailed" ] ; then       
+      local messages failMsg
+      messages=$(tail -n +${lineCount} "${UNIT_OUTPUT_LOG}") || true
+      
+      # debug process "connect failed with messages:"
+      # echo "$messages" >&3
+
+      while true ; do
+        if echo "$messages" | grep -E '^ssh: Could not resolve hostname' ; then
+          failMsg="ssh: Could not resolve hostname"
+          break
+        fi
+        if echo "$messages" | grep -E '^ssh:.*Connection refused' ; then
+          failMsg="ssh: Connection refused"
+          break
+        fi
+        if echo "$messages" | grep -E '^tar:' ; then
+          failMsg="tar error"
+          break
+        fi
+        if echo "$messages" | grep -E '^mkdir:' ; then
+          failMsg="mkdir error"
+          break
+        fi
+
+        failMsg="unknown"
+        break
+      done
+  
+      warn "unit id ${UNIT_ID}, got $failMsg"
+      setVar "TRANSFER_FAIL_MSG" "$failMsg" "$UNIT_FILE"    
+
       if [ $connRetryCount -lt "$MIG_CONN_ATTEMPTS" ] ; then 
         warn "unit id ${UNIT_ID}, connect attempt ${connRetryCount} failed to ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT},passwd=${PASSWD_PRESENT} status:${STATUS}"        
         setVar "MIG_CONN_RETRIES" "$connRetryCount" "$UNIT_FILE"
         setVar "DUE_TS" "$((now + timeTillNext))" "$UNIT_FILE"
         inform "unit id ${UNIT_ID}, will retry in ${timeTillNext} seconds"
         moveFile "$UNIT_FILE" "${UNIT_DIR}" "${UNIT_ID}" || fail "failed to restore unit file"      
-      else      
+      else
         unitFailed "$UNIT_ID" "$UNIT_FILE" "failed ${connRetryCount} attempts to transmit configuration in ${CFG_ARCHIVE} to  ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT},passwd=${PASSWD_PRESENT} status:${STATUS}"
       fi                  
       return 0
-    fi
-  else
-    if [ -n "$MIG_CFG_DIR" ] && [ -d "$MIG_CFG_DIR" ] ; then
-      # TODO: same as above
-      if ! sendDir "$MIG_CFG_DIR" "$TGT_DIR" "$MIG_TX_TIMEOUT" ; then        
-        if [ $connRetryCount -lt "$MIG_CONN_ATTEMPTS" ] ; then 
-          warn "unit id ${UNIT_ID}, connect attempt ${connRetryCount} failed to ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT},passwd=${PASSWD_PRESENT} status:${STATUS}"        
-          setVar "MIG_CONN_RETRIES" "$connRetryCount" "$UNIT_FILE"          
-          setVar "DUE_TS" "$((now + timeTillNext))" "$UNIT_FILE"
-          inform "unit id ${UNIT_ID}, will retry in ${timeTillNext} seconds"
-          moveFile "$UNIT_FILE" "${UNIT_DIR}" "${UNIT_ID}" || fail "failed to restore unit file"      
-        else      
-          unitFailed "$UNIT_ID" "$UNIT_FILE" "failed ${connRetryCount} attempts to transmit configuration in ${MIG_CFG_DIR} to ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT},passwd=${PASSWD_PRESENT} status:${STATUS}"
-        fi                  
-        return 0
-      fi
-    fi
   fi
+
 
   inform "unit id ${UNIT_ID}, registering device with MIG_APP=$MIG_APP"
   local tmpStr
diff --git a/util/migdb-stats b/util/migdb-stats
--- a/util/migdb-stats
+++ b/util/migdb-stats
@@ -3,6 +3,10 @@
 
 set -o errexit -o pipefail
 
+DEBUG_FUNCTS="process"
+LOG_DEBUG=FALSE
+
+
 MIG_DB_DIR=${MIG_DB_DIR="."}
 
 MIG_OUTPUT=${MIG_OUTPUT=stdout}
@@ -21,8 +25,8 @@ else
   exit 1
 fi
 
-MIG_LOG_FILE=stderr
-logTo "$MIG_LOG_FILE"
+MIG_LOG_TO="stderr"
+logTo "$MIG_LOG_TO"
 
 function printHelp {
   cat << EOI >&2
@@ -90,6 +94,88 @@ function getCmdArgs {
   done
 }
 
+function process {
+  local file fail ok modified id duplicate
+  file=$1
+
+  debug process "processing file ${file}"
+  if [[ ! $file =~ .*/db/(done/unit|fail/fail)-(.+)-.{3}$ ]] ; then
+    debug process "file rejected ${file}"
+    return 1
+  fi
+
+  id="${BASH_REMATCH[2]}"
+
+  modified=$(stat --format=%y "${file}")
+  STATUS=
+	DEVICE_ID=
+	FAIL_MSG=
+  
+	tmpFile=$(mktemp)
+  sed 's/\([^=]\+=\)\([^"].*[^"]\)$/\1\"\2\"/g' "${file}" > "${tmpFile}"
+
+  # shellcheck disable=SC1090		 
+  source "${tmpFile}" || fail "failed to source $file"
+
+  debug process "<${UNIT_ID}> == <${id}>"
+
+	if [ "${UNIT_ID}" != "${id}" ] ; then 
+	  warn "invalid file ${entry} skipping "
+    return 1
+	fi
+
+  if [[ ${UNIT_IDS[@]} =~ ${id} ]] ; then 
+    duplicate=1
+  else
+    duplicate=0
+    UNIT_IDS+=(${id})
+  fi
+
+  if [ "${BASH_REMATCH[1]}" == "fail" ] ; then 
+    fail=1
+    ok=0    
+  else   
+    fail=0
+    ok=1
+  fi
+
+  # cat "$tmpFile" >&2
+  rm "${tmpFile}"
+
+  local migDur=0
+  if [ -n "$CREATE_TS" ] && [ -n "$STATUS_TS" ] ; then 
+    migDur=$((STATUS_TS-CREATE_TS))    
+  fi
+  
+	notReached=0
+	migrateErr=0
+	migrateExec=0
+	noShow=0
+	other=0
+
+  if [ "$fail" == "1" ] ; then 
+    if [[ $FAIL_MSG =~ failed\ [0-9]+\ attempts\ to\ transmit\ configuration.* ]] ; then 
+      notReached=1
+          else  
+      if [[ $FAIL_MSG =~ cannot\ find\ success\ message.* ]] ; then
+        migrateErr=1
+      else 
+        if [[ $FAIL_MSG =~ .*Device\ has\ not\ shown\ up\ in\ balena-cloud.* ]] ; then 
+          noShow=1
+        else
+          if [[ $FAIL_MSG =~ failed\ to\ execute\ migrate\ script.* ]] ; then
+            migrateExec=1
+          else     	
+            other=1
+          fi	
+        fi	    
+      fi		  
+    fi
+  fi
+
+  echo "\"${UNIT_ID}\";$migDur;${CREATE_ISOTS};${MIGRATED_ISOTS};${DONE_ISOTS};${modified};$ok;$fail;${notReached};${migrateErr};${migrateExec};${noShow};${other};\"${STATUS}\";\"${DEVICE_ID}\";\"${FAIL_MSG}\";${MIG_CONN_RETRIES};\"${TRANSFER_FAIL_MSG}\";${duplicate}" >&5
+}
+
 
 #############################################
 # main 
@@ -98,6 +184,8 @@ function getCmdArgs {
 getCmdArgs "$@"
 
 setLogFile
+
+UNIT_IDS=()
 
 case "$MIG_OUTPUT" in 
 	stdout|"")
@@ -114,84 +202,19 @@ case "$MIG_OUTPUT" in
 		;;
 esac
 
-inform "scanning ${failDir}" 
+echo "id;dur;created;migrated;done;modified;ok;fail;not reached;no success;migrate err;no show;other;last-status;dev-id;failmsg;retries;txFailMsg;duplicate" >&5
 
-echo "id;created;migrated;done;modified;ok;fail;not reached;no success;migrate err;no show;other;status;last-status;dev-id;failmsg" >&5
+inform "scanning ${failDir}" 
 
 for  entry in "${failDir}/"*
 do 
-  if [[ $entry =~ .*/db/fail/fail-(.+)-.{3}$ ]] ; then
-	id="${BASH_REMATCH[1]}"
-	modified=$(stat --format=%y "${entry}")
-	STATUS=
-	DEVICE_ID=
-	FAIL_MSG=
-	if ! grep -E 'FAIL_MSG=\".*\"' "${entry}" > /dev/null ; then 
-	  tmpFile=$(mktemp)
-     	  sed 's/^FAIL_MSG=\(.*\)$/FAIL_MSG="\1"/g' "${entry}" > "${tmpFile}"
-
-		# shellcheck disable=SC1090		 
-			source "${tmpFile}"
-			rm "${tmpFile}"
-  	else
-			# shellcheck disable=SC1090		 
-			source "${entry}"
-  	fi	
-	if [ "${UNIT_ID}" != "${id}" ] ; then 
-	  warn "invalid file ${entry} skipping "
-	fi
-	
-	notReached=0
-	migrateErr=0
-	migrateExec=0
-	noShow=0
-	other=0
-	
-	if [[ $FAIL_MSG =~ failed\ [0-9]+\ attempts\ to\ transmit\ configuration.* ]] ; then 
-	  notReached=1
-        else  
-	  if [[ $FAIL_MSG =~ cannot\ find\ success\ message.* ]] ; then
-	     migrateErr=1
-	  else 
-	    if [[ $FAIL_MSG =~ .*Device\ has\ not\ shown\ up\ in\ balena-cloud.* ]] ; then 
-		noShow=1
-	    else
-		if [[ $FAIL_MSG =~ failed\ to\ execute\ migrate\ script.* ]] ; then
-   		  migrateExec=1
-		else     	
-		  other=1
-	        fi	
-	    fi	    
-          fi		  
-  	fi
-
-  
-	echo "\"${id}\";${CREATE_ISOTS};${MIGRATED_ISOTS};${DONE_ISOTS};${modified};0;1;${notReached};${migrateErr};${migrateExec};${noShow};${other};\"FAILED\";\"${STATUS}\";${DEVICE_ID};\"${FAIL_MSG}\"" >&5
-  fi 
+  process "$entry" || true
 done
 
+inform "scanning ${doneDir}" 
 
 for  entry in "${doneDir}/"*
 do
-  if [[ $entry =~ .*/db/done/unit-(.+)-.{3}$ ]] ; then
-        id="${BASH_REMATCH[1]}"
-        modified=$(stat --format=%y "${entry}")
-        STATUS=
-        DEVICE_ID=
-        FAIL_MSG=
-        if ! grep -E 'FAIL_MSG=\".*\"' "${entry}" > /dev/null ; then
-          tmpFile=$(mktemp)
-          sed 's/^FAIL_MSG=\(.*\)$/FAIL_MSG="\1"/g' "${entry}" > "${tmpFile}"
-          source "${tmpFile}"
-          rm "${tmpFile}"
-        else
-          source "${entry}"
-        fi
-        if [ "${UNIT_ID}" != "${id}" ] ; then
-          warn "invalid file ${entry} skipping " >2
-        fi
-        echo "\"${id}\";${CREATE_ISOTS};${MIGRATED_ISOTS};${DONE_ISOTS};${modified};1;0;0;0;0;0;0;\"${STATUS}\";\"MIGRATED\";${DEVICE_ID};\"${FAIL_MSG}\"" >&5
-  fi
+  process "$entry" || true
 done
-
 
