changes to README.md and balena-migrate

diff --git a/migratecfg/balena-migrate b/migratecfg/balena-migrate
--- a/migratecfg/balena-migrate
+++ b/migratecfg/balena-migrate
@@ -8,6 +8,7 @@
 # TODO: parted not installed on default beaglebone debian install,
 #       install or replace
 # TODO: add -r --reboot cmdline parameters
+# TODO: support zip archived images - convert o gzip
 #
 ####################################################################
 
@@ -159,6 +160,10 @@ function simulate {
 }
 
 function clean {
+    if [ - n "$TMP_DIR" ] && [ -d "$TMP_DIR" ] ; then
+      rm -rf "$TMP_DIR"
+    fi
+
     if [ -n "$RESTORE_BOOT_CFG_STAGE1" ] ; then
       $RESTORE_BOOT_CFG_STAGE1
     fi
@@ -1022,7 +1027,7 @@ inform "establishing required programs"
 #       possible candidates: parted (on debian, beaglebone) blkid
 
 INITRAM_REQUIRED_PGMS="cat cp dd df dirname echo expr grep gzip ls lsblk mkdir mv parted partprobe reboot stat sync touch udevadm"
-REQUIRED_PGMS="awk findmnt lsblk mkinitramfs parted readlink sed openssl"
+REQUIRED_PGMS="awk file findmnt lsblk mkinitramfs parted readlink sed openssl"
 checkPgms $REQUIRED_PGMS
 
 inform "checked required programs"
@@ -1045,6 +1050,38 @@ inform "HOME_DIR=$HOME_DIR"
 
 if [ -z "$IMAGE_NAME" ] || [ ! -f "${HOME_DIR}/$IMAGE_NAME" ] ; then
   fail "missing image file: $IMAGE_NAME"
+fi
+
+##########################################
+# check / repack image file
+##########################################
+
+TMP_IMG="${HOME_DIR}/${IMAGE_NAME}"
+FTYPE=$(file -b "${TMP_IMG}")
+
+if [[ ! $FTYPE =~ ^gzip\ compressed\ data.* ]] ; then
+  if [[ $FTYPE =~ ^Zip\ archive\ data.* ]]  ; then
+    inform "image file appears to be a zip archive, unzipping and repacking in gzip format.."
+    TMP_DIR=$(mktemp -d -p ./)
+    unzip "${TMP_IMG}" -d "$TMP_DIR" || fail "failed to unzip ${TMP_IMG}"
+    TMP_IMG="${TMP_DIR}/$(ls "$TMP_DIR")"
+    inform "got ${TMP_IMG}"
+    FTYPE=$(file -b "$TMP_IMG")
+  fi
+
+  if [[ $FTYPE =~ ^DOS/MBR\ boot\ sector.* ]]  ; then
+    gzip "$TMP_IMG" || fail "failed to gzip $TMP_IMG"
+    TMP_IMG=$(basename "${TMP_IMG}")
+    IMAGE_NAME="${TMP_DIR}/${TMP_IMG}"
+    inform "working with image $IMAGE_NAME"
+  else
+    fail "cannot make sense of unzipped image file $TMP_IMG - expecting an image file, got $FTYPE"
+  fi
+else
+  FTYPE=$(file -bz "${HOME_DIR}/${IMAGE_NAME}")
+  if [[ ! $FTYPE =~ ^DOS/MBR\ boot\ sector.* ]]  ; then
+    fail "cannot make sense of image file $TMP_IMG - expecting a gzipped image file, got $FTYPE"
+  fi
 fi
 
 ##########################################
diff --git a/migratecfg/extract b/migratecfg/extract
--- a/migratecfg/extract
+++ b/migratecfg/extract
@@ -88,19 +88,27 @@ if [ -z "$IMG_FILE" ] && [ -z "$GRUB_FILE" ] ; then
   fail "no output files specified, please use --img and/or --grub options to specify output files"
 fi
 
-echo "processing image $INPUT_IMG"
+FTYPE=$(file -b "$INPUT_IMG")
 
-if [[ "$INPUT_IMG" =~ .*\.zip$ ]] ; then
+if [[ $FTYPE =~ ^Zip\ archive\ data.* ]]  ; then
   echo "file appears to be a zip archive, unzipping.."
   TMP_DIR=$(mktemp -d -p ./)
   unzip "$INPUT_IMG" -d "$TMP_DIR" || fail "failed to unzip $INPUT_IMG"
   INPUT_IMG="${TMP_DIR}/$(ls "$TMP_DIR")"
   echo "got ${INPUT_IMG}"
+  FTYPE=$(file -b "$INPUT_IMG")
 fi
+
+if [[ ! $FTYPE =~ ^DOS/MBR\ boot\ sector.* ]]  ; then
+  fail "cannot make sense of image file $INPUT_IMG - expecting an image file, got $FTYPE"
+fi
+
 
 if [[ ! "$INPUT_IMG" =~ ^[^\ ]+\.img$ ]] ; then
   fail "cannot make sense of image file $INPUT_IMG - expecting a single file that ends with .img"
 fi
+
+echo "processing image $INPUT_IMG"
 
 while read line
 do
@@ -149,8 +157,8 @@ if [ -n "$IMG_FILE" ] ; then
   echo "mounting root-A"
   mount $LOOP_DEV "$MNT_DIR"
 
-  cp "${MNT_DIR}/opt/resin-image-genericx86-64.resinos-img" "$IMG_FILE" || fail "failed to copy image file"
-  echo "copied ${MNT_DIR}/opt/resin-image-genericx86-64.resinos-img $IMG_FILE"
+  gzip -c "${MNT_DIR}/opt/resin-image-genericx86-64.resinos-img" > "$IMG_FILE" || fail "failed to copy image file"
+  echo "gzipped ${MNT_DIR}/opt/resin-image-genericx86-64.resinos-img to $IMG_FILE"
   sleep 1 # otherwise mount dir might still be busy...
 
   umount "$MNT_DIR" || fail "failed to unmount root-A partition"
