work on documentation and backup scripts

diff --git a/migratecfg/balena-migrate b/migratecfg/balena-migrate
--- a/migratecfg/balena-migrate
+++ b/migratecfg/balena-migrate
@@ -184,7 +184,7 @@ function fail {
 ##########################################
 
 function printHelp {
-  echo "balena-stage1"
+  echo "balena-migrate"
   echo "  prepare host for migration to balena-os"
   echo "  USAGE balena-stage1 [OPTIONS]"
   echo "  please run as root"
@@ -1026,7 +1026,7 @@ inform "establishing required programs"
 # TODO: Check / install tools needed for initramfs too
 #       possible candidates: parted (on debian, beaglebone) blkid
 
-INITRAM_REQUIRED_PGMS="cat cp dd df dirname echo expr grep gzip ls lsblk mkdir mv parted partprobe reboot stat sync touch udevadm"
+INITRAM_REQUIRED_PGMS="cat cp dd df dirname echo expr grep gzip ls lsblk mkdir mv parted partprobe reboot sleep stat sync touch udevadm"
 REQUIRED_PGMS="awk file findmnt lsblk mkinitramfs parted readlink sed openssl"
 checkPgms $REQUIRED_PGMS
 
@@ -1381,10 +1381,14 @@ fi
 ###########################
 
 if [ -n "$BACKUP_FILE" ] ; then
-  if [ -n "$BACKUP_SCRIPT" ] && [ -f "${HOME_DIR}/${BACKUP_SCRIPT}" ] ; then
-    inform "invoking backup script using: ${HOME_DIR}/${BACKUP_SCRIPT} ${HOME_DIR}/${BACKUP_FILE}"
-    ${HOME_DIR}/${BACKUP_SCRIPT} ${HOME_DIR}/${BACKUP_FILE} || fail "backup script ${HOME_DIR}/${BACKUP_SCRIPT} returned error code"
-    inform "...done"
+  if [ -n "$BACKUP_SCRIPT" ] ; then
+    if [ -f "${HOME_DIR}/${BACKUP_SCRIPT}" ] ; then
+      inform "invoking backup script using: ${HOME_DIR}/${BACKUP_SCRIPT} ${HOME_DIR}/${BACKUP_FILE}"
+      ${HOME_DIR}/${BACKUP_SCRIPT} ${HOME_DIR}/${BACKUP_FILE} || fail "backup script ${HOME_DIR}/${BACKUP_SCRIPT} returned error code"
+      inform "...done"
+    else
+      fail "cannot find backup script: ${HOME_DIR}/${BACKUP_SCRIPT}"
+    fi
   else
     if [ -n "$BACKUP_DIRECTORIES" ] ; then
       if [ -f "${HOME_DIR}/$BACKUP_FILE" ] ; then
