added config & procedures to use boot.img / core.img in grub installation

diff --git a/migratecfg/balena-migrate b/migratecfg/balena-migrate
--- a/migratecfg/balena-migrate
+++ b/migratecfg/balena-migrate
@@ -746,17 +746,11 @@ function setupBootCfg_bb {
 ## setup intel device to boot with initramfs
 ####################################################
 
-function setupBootCfg_other {
-  inform "setupBootCfg_other"
+function setupBootCfg_x86 {
+  inform "setupBootCfg_x86"
   # TODO: grub boot device is set in $GRUB_BOOT_DEV - try to determine it from setup (eg. grub.conf)
   # TODO: assuming we are on debian like OS
 
-  INITRAM_REQUIRED_PGMS="${INITRAM_REQUIRED_PGMS} grub-install busybox"
-
-  # make sure BUSYBOX is used & **most** modules are present
-  inform "checking initramfs-tools config"
-  sed -i 's/^\(BUSYBOX\s*=\s*\).*$/\1y/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
-  sed -i 's/^\(MODULES\s*=\s*\).*$/\1most/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
 
   # check if this is an uefi booted system
   local efiBootMgr=$(whereis -b efibootmgr | awk '{ print $2}')
@@ -815,9 +809,26 @@ function setupBootCfg_other {
       fail "grub configuration not found"
   fi
 
-# TODO: make grub HD num from hdDev, just assuming 0 for now
+  if [ -n "$GRUB_BOOT_IMG" ] && [ -n "$GRUB_CORE_IMG" ] ; then
+    # attempt to flash boot images
+    if [ ! -f "${HOME_DIR}/${GRUB_BOOT_IMG}" ] || [ ! -f "${HOME_DIR}/${GRUB_CORE_IMG}" ] ; then
+      fail "could not locate boot images in ${HOME_DIR}/${GRUB_BOOT_IMG}, ${HOME_DIR}/${GRUB_CORE_IMG}"
+    fi
+    # might not need this at all for boot image grub
+    inform "checking initramfs-tools config"
+    sed -i 's/^\(MODULES\s*=\s*\).*$/\1most/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
+    GRUB_INSTALL=
+  else
+    # attempt to install grub from initramfs
+    INITRAM_REQUIRED_PGMS="${INITRAM_REQUIRED_PGMS} grub-install busybox"
+    # make sure BUSYBOX is used & **most** modules are present
 
-  GRUB_INSTALL="TRUE"
+    inform "checking initramfs-tools config"
+    sed -i 's/^\(BUSYBOX\s*=\s*\).*$/\1y/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
+    sed -i 's/^\(MODULES\s*=\s*\).*$/\1most/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
+    GRUB_INSTALL="TRUE"
+  fi
+
 
   if [ -n "$GRUB_CFG" ] ; then
     if [ ! -f "${HOME_DIR}/${GRUB_CFG}" ] ; then
@@ -838,17 +849,17 @@ EOI
   fi
 
 
-  if [ ! "$NO_SETUP" == "TRUE" ] ; then
+  if [ "$NO_SETUP" != "TRUE" ] ; then
 
-    debug setupBootCfg_other "looking for boot device blkid"
+    debug setupBootCfg_x86 "looking for boot device blkid"
 
     if [ -d /dev/disk/by-uuid ] ; then
       for fname in /dev/disk/by-uuid/* ; do
-        debug setupBootCfg_other "looking at $fname"
+        debug setupBootCfg_x86 "looking at $fname"
         linkedFile=$(readlink ${fname})
-        debug setupBootCfg_other "go <${linkedFile}>"
+        debug setupBootCfg_x86 "go <${linkedFile}>"
         if [ "$(basename $ROOT_FS)" == "$(basename $linkedFile)" ] ; then
-          # debug setupBootCfg_other "found ${uuid} for ${ROOT_FS}"
+          # debug setupBootCfg_x86 "found ${uuid} for ${ROOT_FS}"
           partId=$(basename "$fname")
           break
         fi
@@ -1211,9 +1222,9 @@ case "$devType" in
       inform "performing boot setup for Beaglebone: $devType"
       setupBootCfg_bb
     ;;
-    *)
+    x86_64|i686)
       inform "performing boot setup for other: $devType"
-      setupBootCfg_other
+      setupBootCfg_x86
     ;;
 esac
 
@@ -1339,6 +1350,8 @@ GRUB_INSTALL=${GRUB_INSTALL}
 GRUB_CFG="$GRUB_CFG"
 GRUB_BOOT_TYPE=${GRUB_BOOT_TYPE}
 GRUB_PART_GPT=${GPT_TABLE}
+GRUB_BOOT_IMG=${GRUB_BOOT_IMG}
+GRUB_CORE_IMG=${GRUB_CORE_IMG}
 
 BALENA_CONFIG="${BALENA_CONFIG}"
 MEM_MIN_FREE=${MEM_MIN_FREE_S2}
@@ -1428,7 +1441,6 @@ if [ -f "${HOME_DIR}/${BACKUP_FILE}" ] ; then
   inform "backup file size: ${tmp} kB "
   leftMem=`expr ${leftMem} - ${tmp}`
 fi
-
 
 fType=$(file "${HOME_DIR}/${INITRAMFS_NAME}")
 if [[ "$fType" =~ ^[^:]+:.*cpio\ archive.* ]] ; then
diff --git a/migratecfg/initramfs-tools/scripts/local-bottom/balena-stage2-default b/migratecfg/initramfs-tools/scripts/local-bottom/balena-stage2-default
--- a/migratecfg/initramfs-tools/scripts/local-bottom/balena-stage2-default
+++ b/migratecfg/initramfs-tools/scripts/local-bottom/balena-stage2-default
@@ -205,60 +205,90 @@ fi
 # install grub bootloader if required
 ######################################################################
 
-if [ "$GRUB_INSTALL" = "TRUE" ] ; then
-	log "attempting grub install with type $GRUB_BOOT_TYPE"
+## ALT no grub install
+## taken from resin-init-flasher-board STEM ver 2.26.0-rev2
+#if [ -z $INSTALL_UEFI ]; then
+#    echo "[resin-init-flasher-board] non-UEFI installation."
+#    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/EFI"
+#    dd if=/mnt/boot/grub/boot.img of=/dev/$internal_dev conv=fdatasync bs=1M
+#    dd if=/mnt/boot/grub/core.img of=/dev/$internal_dev conv=fdatasync bs=512 seek=1
+#else
+#    echo "[resin-init-flasher-board] UEFI installation."
+#    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/grub"
+#fi
 
-	# if [ "${FLASH_BOOTLOADER}" == "TRUE" ] ; then
-	# 		inform "flashing boot.img os to ${ORIG_BOOT_DEV}"
-	# 		dd if=${BOOT_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1
-	# 		inform "flashing core.img os to ${ORIG_BOOT_DEV}"
-	# 		dd if=${CORE_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1 seek=512
-	# fi
 
-	if [ "$GRUB_BOOT_TYPE" = "legacy" ] ; then
-		######################################################################
-		# install grub legacy bootloader
-		######################################################################
-
-		if [ -f ${MIGRATE_TMP}/grub.cfg ] ; then
-			log "copying grub.cfg"
-			mkdir -p ${BOOT_MNT_DIR}/grub >>$LOG_TO 2>&1 || fail "failed to create directory ${BOOT_MNT_DIR}/grub"
-			cp ${MIGRATE_TMP}/grub.cfg ${BOOT_MNT_DIR}/grub/ >>$LOG_TO 2>&1 || fail "failed to copy ${MIGRATE_TMP}/grub.cfg"
-		else
-			fail "no grub config found"
-		fi
-
-		if [ -d "${BOOT_MNT_DIR}/EFI" ]  ; then
-			log "deleting ${BOOT_MNT_DIR}/EFI"
-			rm -rf ${BOOT_MNT_DIR}/EFI >>"$LOG_TO" 2>&1 || log "failed to delete ${BOOT_MNT_DIR}/EFI"
-		fi
-
-		GRUB_CMD="grub-install 	--no-floppy --boot-directory=${BOOT_MNT_DIR}"
-		GRUB_CMD="${GRUB_CMD} ${BOOT_DEV}"
-
-		$GRUB_CMD >>"$LOG_TO" 2>&1 || fail "failed to install grub with $GRUB_CMD"
+if [ -n "$GRUB_INSTALL"] ; then
+	if [ -f ${MIGRATE_TMP}/grub.cfg ] ; then
+		log "copying grub.cfg"
+		mkdir -p ${BOOT_MNT_DIR}/grub >>$LOG_TO 2>&1 || fail "failed to create directory ${BOOT_MNT_DIR}/grub"
+		cp ${MIGRATE_TMP}/grub.cfg ${BOOT_MNT_DIR}/grub/ >>$LOG_TO 2>&1 || fail "failed to copy ${MIGRATE_TMP}/grub.cfg"
 	else
-		# 									 \
-		######################################################################
-		# install grub UEFI bootloader
-		######################################################################
+		fail "no grub config found"
+	fi
 
-		log "Add UEFI boot entry for starting resinOS from internal media."
-
-		if [ -f ${MIGRATE_TMP}/grub.cfg ] ; then
-			log "copying grub.cfg"
-			cp ${MIGRATE_TMP}/grub.cfg  ${BOOT_MNT_DIR}/EFI/BOOT/ >>$LOG_TO 2>&1 || fail "failed to copy ${MIGRATE_TMP}/grub.cfg"
+	if [ "$GRUB_INSTALL" = "FLASH" ] ; then
+		if [ -f "${MIGRATE_TMP}/boot.img" ] && [ -f "${MIGRATE_TMP}/core.img" ] ; then
+			# install grub img files
+			if [ -d "${BOOT_MNT_DIR}/EFI" ]  ; then
+				log "deleting ${BOOT_MNT_DIR}/EFI"
+				rm -rf ${BOOT_MNT_DIR}/EFI >>"$LOG_TO" 2>&1 || log "failed to delete ${BOOT_MNT_DIR}/EFI"
+			fi
+			dd if="${MIGRATE_TMP}/boot.img" of=dd of=${BOOT_DEV} conv=fdatasync bs=1M >>"$LOG_TO" 2>&1 || log "failed to flash ${MIGRATE_TMP}/boot.img"
+			dd if="${MIGRATE_TMP}/core.img" of=${BOOT_DEV} conv=fdatasync bs=512 seek=1	>>"$LOG_TO" 2>&1 || log "failed to flash ${MIGRATE_TMP}/core.img"
 		else
-			fail "no grub config found"
+			log "warning: grub images not found, falling back to grub-install"
+			GRUB_INSTALL="INSTALL"
 		fi
+	fi
 
-		efibootmgr -c -d ${BOOT_DEV} -p 1 -L "resinOS" -l "\EFI\BOOT\bootx64.efi" || fail "failed to install uefi boot manager with: efibootmgr -c -d ${BOOT_DEV} -p 1 -L resinOS -l \EFI\BOOT\bootx64.efi"
-#
-#		log "attempting grub-install 	--no-floppy --efi-directory=${BOOT_MNT_DIR} --boot-directory=${BOOT_MNT_DIR}"
-#		grub-install 	--no-floppy \
-#									--efi-directory=${BOOT_MNT_DIR} \
-#									--boot-directory=${BOOT_MNT_DIR} \
-#									${BOOT_DEV} >>"$LOG_TO" 2>&1 || fail "failed to install grub"
+	if [ "$GRUB_INSTALL" = "INSTALL" ] ; then
+		log "attempting grub install with type $GRUB_BOOT_TYPE"
+
+		# if [ "${FLASH_BOOTLOADER}" == "TRUE" ] ; then
+		# 		inform "flashing boot.img os to ${ORIG_BOOT_DEV}"
+		# 		dd if=${BOOT_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1
+		# 		inform "flashing core.img os to ${ORIG_BOOT_DEV}"
+		# 		dd if=${CORE_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1 seek=512
+		# fi
+
+		if [ "$GRUB_BOOT_TYPE" = "legacy" ] ; then
+			######################################################################
+			# install grub legacy bootloader
+			######################################################################
+
+			if [ -d "${BOOT_MNT_DIR}/EFI" ]  ; then
+				log "deleting ${BOOT_MNT_DIR}/EFI"
+				rm -rf ${BOOT_MNT_DIR}/EFI >>"$LOG_TO" 2>&1 || log "failed to delete ${BOOT_MNT_DIR}/EFI"
+			fi
+
+			GRUB_CMD="grub-install 	--no-floppy --boot-directory=${BOOT_MNT_DIR}"
+			GRUB_CMD="${GRUB_CMD} ${BOOT_DEV}"
+
+			$GRUB_CMD >>"$LOG_TO" 2>&1 || fail "failed to install grub with $GRUB_CMD"
+		else
+			# 									 \
+			######################################################################
+			# install grub UEFI bootloader
+			######################################################################
+
+			log "Add UEFI boot entry for starting resinOS from internal media."
+
+			if [ -f ${MIGRATE_TMP}/grub.cfg ] ; then
+				log "copying grub.cfg"
+				cp ${MIGRATE_TMP}/grub.cfg  ${BOOT_MNT_DIR}/EFI/BOOT/ >>$LOG_TO 2>&1 || fail "failed to copy ${MIGRATE_TMP}/grub.cfg"
+			else
+				fail "no grub config found"
+			fi
+
+			efibootmgr -c -d ${BOOT_DEV} -p 1 -L "resinOS" -l "\EFI\BOOT\bootx64.efi" || fail "failed to install uefi boot manager with: efibootmgr -c -d ${BOOT_DEV} -p 1 -L resinOS -l \EFI\BOOT\bootx64.efi"
+	#
+	#		log "attempting grub-install 	--no-floppy --efi-directory=${BOOT_MNT_DIR} --boot-directory=${BOOT_MNT_DIR}"
+	#		grub-install 	--no-floppy \
+	#									--efi-directory=${BOOT_MNT_DIR} \
+	#									--boot-directory=${BOOT_MNT_DIR} \
+	#									${BOOT_DEV} >>"$LOG_TO" 2>&1 || fail "failed to install grub"
+		fi
 	fi
 fi
 
