cosmetic

diff --git a/migratecfg/balena-stage1 b/migratecfg/balena-stage1
--- a/migratecfg/balena-stage1
+++ b/migratecfg/balena-stage1
@@ -34,8 +34,8 @@ GRUB_BOOT_TYPE="legacy"
 NO_FLASH= #"TRUE"
 ERROR_EXIT= # "reboot -f"
 
-# DEBUG: do not modify config.txt if set to "TRUE"
-NO_SETUP= #"TRUE"
+# DEBUG: do not modify config.txt, cmdline.txt, grub config if set to "TRUE"
+NO_SETUP= #{ }"TRUE"
 # create initramfs in contrast to using an initramfs supplied
 MK_INITRAMFS="TRUE"
 # name of initramfs to be created/used expected in $HOMEDIR
@@ -354,50 +354,57 @@ function setupBootCfg_rpi {
   ##########################
 
   INITRAM_REQUIRED_PGMS="${INITRAM_REQUIRED_PGMS} cp cat rm sleep"
-  inform "making backup of config.txt"
-  CONFIG_TXT_BACKUP="${CONFIG_TXT}.$(date +%Y%m%d-%H-%M-%S)"
-  TMP_FILE=$(mktemp)
-  INITRAM_CMD="initramfs ${INITRAMFS_NAME} followkernel"
 
   # make sure BUSYBOX is NOT used
   inform "checking initramfs-tools config"
   sed -i 's/^\(BUSYBOX\s*=\s*\).*$/\1n/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
   sed -i 's/^\(MODULES\s*=\s*\).*$/\1list/' "${HOME_DIR}/initramfs-tools/initramfs.conf" || fail "failed to modify ${HOME_DIR}/initramfs-tools/initramfs.conf"
 
-  while read -r line
-  do
-    if [[ $line =~ ^\s*\# ]] ; then
-      echo $line >> $TMP_FILE
-      continue
-    fi
 
-    if [[ $line =~ ^\s*initramfs ]] ; then
-      if [ "$line" != "$INITRAM_CMD" ] ; then
-        echo "# $line" >> $TMP_FILE
+  if [ ! "$NO_SETUP" == "TRUE" ] ; then
+    inform "making backup of config.txt"
+
+    CONFIG_TXT_BACKUP="${CONFIG_TXT}.$(date +%Y%m%d-%H-%M-%S)"
+    TMP_FILE=$(mktemp)
+    INITRAM_CMD="initramfs ${INITRAMFS_NAME} followkernel"
+
+
+    while read -r line
+    do
+      if [[ $line =~ ^\s*\# ]] ; then
+        echo $line >> $TMP_FILE
+        continue
       fi
-    else
-      echo $line >> $TMP_FILE
-    fi
-  done < "${CONFIG_TXT}"
-  echo $INITRAM_CMD >> $TMP_FILE
-  cp $TMP_FILE $CONFIG_TXT
-  rm $TMP_FILE
 
-  ###########################
-  ## Modify /boot/cmdline.txt
-  ###########################
+      if [[ $line =~ ^\s*initramfs ]] ; then
+        if [ "$line" != "$INITRAM_CMD" ] ; then
+          echo "# $line" >> $TMP_FILE
+        fi
+      else
+        echo $line >> $TMP_FILE
+      fi
+    done < "${CONFIG_TXT}"
+    echo $INITRAM_CMD >> $TMP_FILE
+    cp $TMP_FILE $CONFIG_TXT
+    rm $TMP_FILE
 
-  if [ "$DEBUG" == "TRUE" ] ; then
-    CMD_LINE=$(cat ${CMDLINE_TXT})
-    if [[ ! $CMD_LINE =~ debug ]] ; then
-      inform "making backup of ${CMDLINE_TXT}"
-      CMDLINE_TXT_BACKUP="${CMDLINE_TXT}.$(date +%Y%m%d-%H-%M-%S)"
-      cp ${CMDLINE_TXT}  ${CMDLINE_TXT_BACKUP}
-    	CMD_LINE="${CMD_LINE} debug"
-    	echo $CMD_LINE > cmdline.txt
+    ###########################
+    ## Modify /boot/cmdline.txt
+    ###########################
+
+    if [ "$DEBUG" == "TRUE" ] ; then
+      CMD_LINE=$(cat ${CMDLINE_TXT})
+      if [[ ! $CMD_LINE =~ debug ]] ; then
+        inform "making backup of ${CMDLINE_TXT}"
+        CMDLINE_TXT_BACKUP="${CMDLINE_TXT}.$(date +%Y%m%d-%H-%M-%S)"
+        cp ${CMDLINE_TXT}  ${CMDLINE_TXT_BACKUP}
+      	CMD_LINE="${CMD_LINE} debug"
+      	echo $CMD_LINE > cmdline.txt
+      fi
     fi
+  else
+      inform "boot setup is disabled, NO_SETUP=$NO_SETUP"
   fi
-
 }
 
 ####################################################
@@ -510,7 +517,8 @@ linux /vmlinuz root=LABEL=resin-rootA rootwait quiet loglevel=0 splash udev.log-
 }
 EOI
 
-cat <<EOI > /etc/grub.d/42_resin
+  if [ ! "$NO_SETUP" == "TRUE" ] ; then
+    cat <<EOI > /etc/grub.d/42_resin
 #!/bin/sh
 exec tail -n +3 \$0
 # This file provides an easy way to add custom menu entries.  Simply type the
@@ -526,12 +534,15 @@ menuentry "resin-migration" {
   initrd  ${KBOOT_DIR}${INITRAMFS_NAME}
 }
 EOI
-chmod +x /etc/grub.d/42_resin
+    chmod +x /etc/grub.d/42_resin
 
-  inform "updating grub config using ${GRUBUPDT}"
-  update-grub || fail "failed to update grub config"
-  inform "calling grub-reboot resin-migration"
-  grub-reboot resin-migration
+    inform "updating grub config using ${GRUBUPDT}"
+    update-grub || fail "failed to update grub config"
+    inform "calling grub-reboot resin-migration"
+    grub-reboot resin-migration
+else
+    inform "boot setup is disabled, NO_SETUP=$NO_SETUP"
+fi
 }
 
 ####################################################################################
@@ -553,7 +564,7 @@ fi
 CONFIG_TXT="/boot/config.txt"
 # raspi cmdline.txt to modify
 CMDLINE_TXT="/boot/cmdline.txt"
-SUPPORTED_OSSES="ubuntu-14.04 raspbian-9"
+SUPPORTED_OSSES="ubuntu-18.04 ubuntu-14.04 raspbian-9"
 SUPPORTED_ARCHS="x86_64 armv7l i686"
 
 RASPI_1_REVS="0002 0003 0004 0005 0006 0007 0008 0009 000d 000e 000f 0010 0011 0012 0013 0014 0015 900092 900093	920093 9000c1 900021 900032 900092 900093 920093 9000c1"
@@ -656,20 +667,13 @@ inform "ROOT_DEV=${ROOT_DEV}"
 ## create boot configuration
 ###########################
 
-if [ ! "$NO_SETUP" == "TRUE" ] ; then
-  inform "boot setup enabled: NO_SETUP=$NO_SETUP"
-  if [ "$IS_PI" == "TRUE" ] ; then
-    inform "performing boot setup for RPI: $IS_PI"
-    setupBootCfg_rpi
-  else
-    inform "performing boot setup for other: $IS_PI"
-    setupBootCfg_other
-  fi
+if [ "$IS_PI" == "TRUE" ] ; then
+  inform "performing boot setup for RPI: $IS_PI"
+  setupBootCfg_rpi
 else
-  inform "boot setup disabled: NO_SETUP=$NO_SETUP"
+  inform "performing boot setup for other: $IS_PI"
+  setupBootCfg_other
 fi
-
-
 
 ###########################
 ## write /etc/migrate.conf
