more cleanup on all scripts

diff --git a/migratecfg/balena-stage1 b/migratecfg/balena-stage1
--- a/migratecfg/balena-stage1
+++ b/migratecfg/balena-stage1
@@ -10,6 +10,7 @@
 ####################################################################
 # TODO: parted not installed on default beaglebone debian install,
 #       install or replace
+# TODO: remove non DEFAULT strategies ?
 ####################################################################
 
 STRATEGY="DEFAULT"
@@ -473,12 +474,31 @@ function setupBootCfg_rpi {
   fi
 }
 
+function undoBootCfg_rpi {
+  if [ "$RESTORE_BOOT" == "TRUE" ] ; then
+    if [ -n "$CONFIG_TXT_BACKUP" ] && [ -f "$CONFIG_TXT_BACKUP" ] ; then
+      cp $CONFIG_TXT_BACKUP $CONFIG_TXT
+    fi
+
+    if [ -n "$CMDLINE_TXT_BACKUP" ] && [ -f "$CMDLINE_TXT_BACKUP" ] ; then
+      cp $CMDLINE_TXT_BACKUP $CMDLINE_TXT
+    fi
+    RESTORE_BOOT=
+  fi
+}
+
+
 ####################################################
 ## setup beaglebone device to boot with initramfs
 ####################################################
 
 function setupBootCfg_bb {
   fail "setupBootCfg_bb not implemented"
+  # modify bbb_uEnv.txt ?
+}
+
+function undoBootCfg_bb {
+  fail "undoBootCfg_bb not implemented"
   # modify bbb_uEnv.txt ?
 }
 
@@ -502,10 +522,6 @@ function setupBootCfg_other {
   local efiBootMgr=$(whereis -b efibootmgr | awk '{ print $2}')
   if [ -n "$efiBootMgr" ] &&  efibootmgr &>/dev/null ; then
     GRUB_BOOT_TYPE="UEFI"
-    # determine EFI/boot partitions
-
-
-
     INITRAM_REQUIRED_PGMS="${INITRAM_REQUIRED_PGMS} efibootmgr" # TODO: might or might not be using it
   fi
 
@@ -619,13 +635,22 @@ menuentry "resin-migration" {
 EOI
     chmod +x /etc/grub.d/42_resin
 
-    inform "updating grub config using ${GRUBUPDT}"
+    inform "updating grub config using update-grub"
     update-grub || fail "failed to update grub config"
     inform "calling grub-reboot resin-migration"
     grub-reboot resin-migration
 else
     inform "boot setup is disabled, NO_SETUP=$NO_SETUP"
 fi
+}
+
+function undoBootCfg_other {
+  if [ "$NO_SETUP" !=  "TRUE" ] && [ -f "/etc/grub.d/42_resin" ] ; then
+    inform "undoing grub boot configuration"
+    rm /etc/grub.d/42_resin || fail "failed to delete /etc/grub.d/42_resin"
+    inform "updating grub config using update-grub"
+    update-grub || fail "failed to update grub config"
+  fi
 }
 
 ####################################################################################
@@ -669,8 +694,8 @@ inform "establishing required programs"
 
 # TODO: Check / install tools needed for initramfs too
 
-INITRAM_REQUIRED_PGMS="mkdir dd gzip df parted echo reboot partprobe sync dirname lsblk udevadm stat touch"
-REQUIRED_PGMS="lsblk readlink mkinitramfs sed findmnt parted" #  gzip
+INITRAM_REQUIRED_PGMS="dd df dirname echo expr grep gzip lsblk mkdir parted partprobe reboot sync stat touch udevadm"
+REQUIRED_PGMS="awk findmnt lsblk mkinitramfs parted readlink sed"
 checkPgms $REQUIRED_PGMS
 
 inform "checked required programs"
@@ -743,8 +768,6 @@ fi
 if [ "$MK_INITRAMFS" == "TRUE" ] && [ ! -d "${HOME_DIR}/initramfs-tools" ] ; then
   fail "missing image directory: ${HOME_DIR}/initramfs-tools"
 fi
-
-# TODO: handle gpt / msdos1 partition tables
 
 getBootInfo
 
@@ -963,7 +986,24 @@ if [ "${MK_INITRAMFS}" == TRUE ] ; then
     fi
 
     inform "creating initramfs: mkinitramfs $OPTS"
-    mkinitramfs $OPTS || fail "failed to create initramfs in ${HOME_DIR}/${INITRAMFS_NAME}"
+    if ! mkinitramfs $OPTS ; then
+      inform "failed to create initramfs in ${HOME_DIR}/${INITRAMFS_NAME} , attempting to undo boot setup"
+      case "$devType" in
+          armv7_rpi*)
+            inform "undoing boot setup for RPI: $devType"
+            undoBootCfg_rpi
+          ;;
+          armv7_bb*)
+            inform "undoing boot setup for Beaglebone: $devType"
+            undoBootCfg_bb
+          ;;
+          *)
+            inform "undoing boot setup for other: $devType"
+            undoBootCfg_other
+          ;;
+      esac
+      fail "failed to create initramfs in ${HOME_DIR}/${INITRAMFS_NAME}"
+    fi
 
     inform "copying ${HOME_DIR}/${INITRAMFS_NAME} to ${BOOT_DIR}/"
     cp ${HOME_DIR}/${INITRAMFS_NAME} "${BOOT_DIR}/" || fail "failed to copy ${HOME_DIR}/${INITRAMFS_NAME} to ${BOOT_DIR}/"
diff --git a/migratecfg/initramfs-tools/hooks/balena-init b/migratecfg/initramfs-tools/hooks/balena-init
--- a/migratecfg/initramfs-tools/hooks/balena-init
+++ b/migratecfg/initramfs-tools/hooks/balena-init
@@ -21,15 +21,25 @@ copyPgm() {
 
     local pgmPath="$(whereis -b $pgm | awk '{ print $2}')"
 
-    # echo "$pgm: -> $pgmPath"
     if [ -z "${pgmPath}" ] ; then
         echo "could not find ${pgmPath}"
     fi
 
-    echo "[balena-init] copy ${pgmPath}"
+    log "copy ${pgmPath}"
 
     copy_exec ${pgmPath}
 }
+
+log() {
+	echo "[$(date +%T) balena-init] $1"
+}
+
+fail() {
+	echo "[$(date +%T) balena-init] $1"
+	echo "[$(date +%T) balena-init] terminating"
+	exit 1
+}
+
 
 ##############################
 # main                       #
@@ -51,24 +61,50 @@ do
     copyPgm ${pgmName}
 done
 
-echo "[balena-init] dest dir ${DESTDIR}"
+log "dest dir ${DESTDIR}"
 
+log "copy /etc/balena-migrate-stage2.conf"
 cp /etc/balena-migrate-stage2.conf "${DESTDIR}/etc/"
+
+MIGRATE_DIR="${DESTDIR}${MIGRATE_TMP}"
+log "creating migrate dir ${MIGRATE_DIR}"
+mkdir -p "$MIGRATE_DIR" || fail "failed to create directory ${MIGRATE_DIR}"
+log "...done"
+
+if [ -n "${BALENA_CONFIG}" ] && [ -f "${HOME_DIR}/${BALENA_CONFIG}" ] ; then
+	log "copying balena config from ${HOME_DIR}/${BALENA_CONFIG} to ${MIGRATE_DIR}/"
+	cp "${HOME_DIR}/${BALENA_CONFIG}" "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/${BALENA_CONFIG}  to ${MIGRATE_DIR}/"
+	log "..done"
+fi
+
+log "copying network config files to initramfs"
+for file in $NETWORK_CONFIGS; do
+	if [ -f "${HOME_DIR}/$file" ] ; then
+		log "copying ${HOME_DIR}/$file"
+		cp "${HOME_DIR}/$file" "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/$fileto ${MIGRATE_DIR}/"
+	else
+		fail "could not find  ${HOME_DIR}/$file"
+	fi
+done
 
 if [ "$GRUB_INSTALL" = "TRUE" ] ; then
 	if [ -d /usr/lib/grub ] ; then
+		log "copy grub env from /usr/lib/grub"
 		mkdir -p ${DESTDIR}/usr/lib/grub
-		cp -r /usr/lib/grub/* ${DESTDIR}/usr/lib/grub
-  fi
+		cp -r /usr/lib/grub/* ${DESTDIR}/usr/lib/grub || fail "failed to copy /usr/lib/grub"
+	else
+		log "/usr/lib/grub does not exist"
+		exit 1
+	fi
 
 	if [ -f ${HOME_DIR}/grub.cfg ] ; then
-		echo "[balena-init] copying ${HOME_DIR}/grub.cfg"
-		cp ${HOME_DIR}/grub.cfg "${DESTDIR}/"
+		log "copying ${HOME_DIR}/grub.cfg"
+		cp ${HOME_DIR}/grub.cfg "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/grub.cfg"
 	fi
 
 	if [ -f ${HOME_DIR}/device.map ] ; then
-		echo "[balena-init] copying ${HOME_DIR}/device.map"
-		cp ${HOME_DIR}/device.map "${DESTDIR}/"
+		log "copying ${HOME_DIR}/device.map"
+		cp ${HOME_DIR}/device.map "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/device.map"
 	fi
 fi
 
diff --git a/migratecfg/initramfs-tools/scripts/local-bottom/balena-stage2-default b/migratecfg/initramfs-tools/scripts/local-bottom/balena-stage2-default
--- a/migratecfg/initramfs-tools/scripts/local-bottom/balena-stage2-default
+++ b/migratecfg/initramfs-tools/scripts/local-bottom/balena-stage2-default
@@ -19,9 +19,9 @@ if [ -f /scripts/functions ] ; then
     . /scripts/functions
 fi
 
-if [ -f /scripts/local ] ; then
-    . /scripts/local
-fi
+# if [ -f /scripts/local ] ; then
+#     . /scripts/local
+# fi
 
 if [ -f /etc/balena-migrate-stage2.conf ] ; then
     . /etc/balena-migrate-stage2.conf
@@ -36,20 +36,21 @@ else
 fi
 
 if [  "$STRATEGY" != "DEFAULT" ] ; then
-    log "local-premount balena-stage2-default not enabled"
+    log "balena-stage2-default not enabled"
     exit 0
 fi
 
-# TODO: make sure required programs are actually present
-
-DEBUG_STAGE2="TRUE"
+# Enable DEBUB output (debug function in balena-common)
+DEBUG_STAGE2=	#"TRUE"
+# Set Failure exit to panic
 FAIL_EXIT="panic"
-
+# initialize log destination
 LOG_TO=
 log_to "${MIGRATE_TMP}/${LOG_FILE}"
 
-log "local-bottom balena-stage2-default started"
+log "balena-stage2-default started"
 
+# enable logging to external destination
 if [ -n "$LOG_DRIVE" ] ; then
 	if mount_device ${LOG_DRIVE} ${LOG_FS_TYPE} ${LOG_MOUNT_DIR} ; then
 		log_to 	"${LOG_MOUNT_DIR}/${LOG_FILE}"
@@ -59,12 +60,14 @@ if [ -n "$LOG_DRIVE" ] ; then
 	fi
 fi
 
-# TODO: restore former boot configuration on raspian
-
+#############################################################
+# Restore former boot configuration on non grub systems
+#############################################################
 if [ "$RESTORE_BOOT" = "TRUE" ] ; then
 	log "attempting to restore boot configuration"
 
 	if [ "$ORIG_BOOT_PART" != "$ORIG_ROOT_PART" ] ; then
+		# attempt to mount boot device
 		if ! mount_device ${ORIG_BOOT_PART} ${ORIG_BOOT_FS_TYPE} /orig-boot ; then
 		 	log "failed to mount ${ORIG_BOOT_PART}"
 		else
@@ -73,11 +76,13 @@ if [ "$RESTORE_BOOT" = "TRUE" ] ; then
 	fi
 
 	if [ -n "$CONFIG_TXT" ] && [ -n "$CONFIG_TXT_BACKUP" ] ; then
+		# attempt restore config.txt on RPI's
 		cp /orig-boot/${CONFIG_TXT_BACKUP} /orig-boot/${CONFIG_TXT} >>"$LOG_TO" 2>&1 || log "failed to copy /orig-boot/${CONFIG_TXT_BACKUP}"
 		log "copied /orig-boot/${CONFIG_TXT_BACKUP} to /orig-boot/${CONFIG_TXT}"
 	fi
 
 	if [ -n "$CMDLINE_TXT" ] && [ -n "$CMDLINE_TXT_BACKUP" ] ; then
+		# attempt restore cmdline.txt on RPI's
 		cp /orig-boot/${CMDLINE_TXT_BACKUP} /orig-boot/${CMDLINE_TXT} >>"$LOG_TO" 2>&1 || log "failed to copy /orig-boot/${CMDLINE_TXT_BACKUP}"
 		log "copied /orig-boot/${CMDLINE_TXT_BACKUP} to /orig-boot/${CMDLINE_TXT}"
 	fi
@@ -87,43 +92,27 @@ if [ "$RESTORE_BOOT" = "TRUE" ] ; then
 		UMOUNT_BOOT=
 	fi
 
-	log "restored original boot configuration"
+	log "done restoring original boot configuration"
 fi
 
+######################################################################
+# make sure we have enough meeory to copy files to initramfs
+######################################################################
 checkMem
 
-log "creating migrate dir ${MIGRATE_TMP}"
-mkdir -p ${MIGRATE_TMP} || fail "failed to create directory ${MIGRATE_TMP}"
 if [ ! -d ${MIGRATE_TMP} ] ; then
-     fail  "failed to create directory in ${MIGRATE_TMP}"
+     fail  "could not find migrate dir: ${MIGRATE_TMP}"
 fi
-log "...done"
 
 log "copying image from ${rootmnt}${HOME_DIR}/${IMAGE_FILE} to ${MIGRATE_TMP}/"
 cp "${rootmnt}${HOME_DIR}/${IMAGE_FILE}" "${MIGRATE_TMP}/" || fail  "failed to copy ${rootmnt}${HOME_DIR}/${IMAGE_FILE}  to ${MIGRATE_TMP}/"
 log "..done"
-
-if [ -n "${BALENA_CONFIG}" ] && [ -f "${rootmnt}${HOME_DIR}/${BALENA_CONFIG}" ] ; then
-	log "copying balena config from ${rootmnt}${HOME_DIR}/${BALENA_CONFIG} to ${MIGRATE_TMP}/"
-	cp "${rootmnt}${HOME_DIR}/${BALENA_CONFIG}" "${MIGRATE_TMP}/" || fail  "failed to copy ${rootmnt}${HOME_DIR}/${BALENA_CONFIG}  to ${MIGRATE_TMP}/"
-	log "..done"
-fi
 
 if [ -f "${rootmnt}${HOME_DIR}/${BACKUP_FILE}" ] ; then
 	log "copying backup from ${rootmnt}${HOME_DIR}/${BACKUP_FILE} to ${MIGRATE_TMP}/"
 	cp "${rootmnt}${HOME_DIR}/${BACKUP_FILE}" "${MIGRATE_TMP}/" || fail  "failed to copy ${rootmnt}${HOME_DIR}/${IMAGE_FILE}  to ${MIGRATE_TMP}/"
 	log "..done"
 fi
-
-log "copying network config files to initramfs"
-if [ -f "${rootmnt}${HOME_DIR}/resin-wifi-01" ] ; then
-	cp "${rootmnt}${HOME_DIR}/resin-wifi-01" "${MIGRATE_TMP}/" >>"$LOG_TO" 2>&1  || log "no network config copied"
-fi
-
-for file in $NETWORK_CONFIGS; do
-	log "copying ${rootmnt}${HOME_DIR}/$file"
-	cp "${rootmnt}${HOME_DIR}/$file" "${MIGRATE_TMP}/$file" >>"$LOG_TO" 2>&1  || log "no network config copied"
-done
 
 log "creating mountpoint on ${BOOT_MNT_DIR}"
 mkdir -p ${BOOT_MNT_DIR} || fail "failed to create directory ${BOOT_MNT_DIR}"
@@ -209,10 +198,10 @@ if [ "$GRUB_INSTALL" = "TRUE" ] ; then
 	if [ "$GRUB_BOOT_TYPE" = "legacy" ] ; then
 		# --grub-mkdevicemap=device.map \
 
-		if [ -f grub.cfg ] ; then
+		if [ -f ${MIGRATE_TMP}/grub.cfg ] ; then
 			log "copying grub.cfg"
 			mkdir -p ${BOOT_MNT_DIR}/grub >>$LOG_TO 2>&1 || fail "failed to create directory ${BOOT_MNT_DIR}/grub"
-			cp grub.cfg ${BOOT_MNT_DIR}/grub/ >>$LOG_TO 2>&1 || fail "failed to copy grub.cfg"
+			cp ${MIGRATE_TMP}/grub.cfg ${BOOT_MNT_DIR}/grub/ >>$LOG_TO 2>&1 || fail "failed to copy ${MIGRATE_TMP}/grub.cfg"
 		else
 			fail "no grub config found"
 		fi
