improvements to logging and error reporting

diff --git a/migratecfg/balena-migrate b/migratecfg/balena-migrate
--- a/migratecfg/balena-migrate
+++ b/migratecfg/balena-migrate
@@ -134,6 +134,7 @@ MAX_BADBLOCKS=
 ################################################################################
 # Min acceptable device write speed
 MIN_WRITE_SPEED=
+WARN_WRITE_SPEED=200
 
 ##########################################
 # log functions
@@ -156,21 +157,29 @@ function color {
 }
 
 function inform {
-    printf "${GREEN}[%s %s] INFO:${NC} %s\n" "$(date +%T)" "${SCRIPT_NAME}" "${1}"
+    local ts
+    ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")  
+    printf "${GREEN}[%s %s] INFO:${NC} %s\n" "$ts" "${SCRIPT_NAME}" "${1}"
 }
 
 function warn {
-    printf "${YELLOW}[%s %s] WARN:${NC} %s\n" "$(date +%T)" "${SCRIPT_NAME}" "${1}"
+    local ts
+    ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")  
+    printf "${YELLOW}[%s %s] WARN:${NC} %s\n" "$ts" "${SCRIPT_NAME}" "${1}"
 }
 
 function debug {
     if [ "$LOG_DEBUG" == "TRUE" ] && listContains "$DEBUG_FUNCTS" "${1}" ; then
-      printf "${BROWN}[%s %s] DEBUG:${NC} %s: %s\n" "$(date +%T)" "${SCRIPT_NAME}" "${1}" "${2}"
+      local ts
+      ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")  
+      printf "${BROWN}[%s %s] DEBUG:${NC} %s: %s\n" "$ts" "${SCRIPT_NAME}" "${1}" "${2}"
     fi
 }
 
 function simulate {
-    printf "${GREEN}[%s %s] INFO:${NC}  %s\n" "$(date +%T)" "${SCRIPT_NAME}" "${1}"
+    local ts
+    ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")  
+    printf "${GREEN}[%s %s] INFO:${NC}  %s\n" "$ts" "${SCRIPT_NAME}" "${1}"
 }
 
 function clean {
@@ -190,7 +199,9 @@ function clean {
 ##########################################
 
 function fail {
-    printf "${RED}[%s %s] ERROR:${NC} %s\n" "$(date +%T)" "${SCRIPT_NAME}" "${1}"
+    local ts
+    ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")  
+    printf "${RED}[%s %s] ERROR:${NC} %s\n" "$ts" "${SCRIPT_NAME}" "${1}"
     clean
     exit -1
 }
@@ -403,6 +414,10 @@ function checkDisk {
   inform "time per 1000/sectors (ms): $((timeWriting*1000/sectorsWritten))"
   local writeSpeed=$((sectorsWritten*sectorSize*1000/timeWriting/1024))
   inform "write speed KB/sec:         ${writeSpeed}"
+
+  if [ -n "$WARN_WRITE_SPEED" ] && [ $WARN_WRITE_SPEED -gt $writeSpeed ] ; then 
+    warn "device write speed appears low: $WARN_WRITE_SPEED > $writeSpeed"
+  fi
 
   if [ -n "$MIN_WRITE_SPEED" ] && [ $MIN_WRITE_SPEED -gt $writeSpeed ] ; then 
     fail "device write speed is less than threshold value ${writeSpeed} < ${MIN_WRITE_SPEED}"
@@ -1257,10 +1272,15 @@ fi
 # shellcheck disable=SC2086
 checkPgms $REQUIRED_PGMS
 
-if [ -f "./checksums.md5" ] && ! md5sum -c "./checksums.md5" >/dev/null ; then 
-  inform "The checksum test failed. Please make sure to compute checksums using the mkCheckSum script on the migrate config after every change."
-  inform "If the checksums were up to date this failure indicates a write error on the device."
-  fail "Terminating due to failed checksum test"
+if [ -f "./checksums.md5" ] ; then 
+  inform "checking md5 checksums of migration environment"
+  if ! md5sum -c "./checksums.md5" ; then 
+    warn "The checksum test failed. Please make sure to compute checksums using the mkCheckSum script on the migrate config after every change."
+    warn "If the checksums were up to date this failure indicates a write error on the device."
+    fail "Terminating due to failed checksum test"
+  fi
+else 
+  warn "checksums.md5 not found, not checking md5 checksums of migration environment"
 fi
 
 inform "found all required programs"
diff --git a/util/migdb-migrate b/util/migdb-migrate
--- a/util/migdb-migrate
+++ b/util/migdb-migrate
@@ -405,10 +405,17 @@ function process {
     return 0
   fi
 
+  errMsg=$(grep -E "\[.*balena-migrate\] +(WARN|ERROR):.*$" < "$cmdLog") || true  
+  if [ -n "$errMsg" ] ; then 
+    warn "unit id ${UNIT_ID}, warnings or error messages found in process log:"
+    echo "${errMsg}" >&3
+  fi
+
   successMsg=$(grep -E "\[[^\]+\]*.INFO:.*migration successful," < "$cmdLog") || true  
   local grepRes=$?
-  rm "$cmdLog" || true
 
+  rm "$cmdLog" || true
+  
   if [ $grepRes -eq 0 ] && [ -n "$successMsg" ] ; then
     if [[ $successMsg =~ .*please\ reboot\ system.* ]] ; then
       inform "unit id ${UNIT_ID}, rebooting device"
@@ -430,6 +437,7 @@ function process {
 
     moveFile "${UNIT_FILE}" "${PROCESS_DIR}" "${UNIT_ID}" || fail "failed to move ${UNIT_FILE} to ${PROCESS_DIR}, ${UNIT_ID}"
     success "unit id ${UNIT_ID}, uuid=${UUID}, successfully finished stage 1 of migration"
+    inform "unit id ${unitId}: log is in $UNIT_OUTPUT_LOG"
   else
     unitFailed "$UNIT_ID" "$UNIT_FILE" "cannot find success message in migrate log from ${MIG_SSH_USER}@${MIG_SSH_HOST}:${MIG_SSH_PORT}"
     return 0
