cleanup stage 2

diff --git a/migratecfg/initramfs-tools/scripts/balena-common b/migratecfg/initramfs-tools/scripts/balena-common
--- a/migratecfg/initramfs-tools/scripts/balena-common
+++ b/migratecfg/initramfs-tools/scripts/balena-common
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+############################################################################
+# Make sure there is enough memory to copy the image file & backup to the
+# initramfs
+############################################################################
+
 checkMem() {
 	totMem=`cat /proc/meminfo | grep "MemTotal:"`
 	totMem=`expr match "$totMem" '[^:]\+:[^0-9]\+\([0-9]\+\)[^0-9]*kB'` || true
@@ -33,58 +38,87 @@ checkMem() {
 	fi
 }
 
+############################################################################
+# Log message to the current log destination
+############################################################################
 
 logMsg() {
 	if [ -z "$LOG_TO" ] ; then
-		fail "logMsg LOG_TO not set"
+		_log_msg "${1}\n"
+	else
+		echo "${1}" >> "$LOG_TO" || _log_msg "${1}\n"
 	fi
-
-	if [ ! -f $LOG_TO ] ; then
-		LOG_DIR=$(dirname $LOG_TO)
-		if [ ! -d $LOG_DIR ] ; then
-			mkdir -p $LOG_DIR	|| fail  "failed to create directory $LOG_DIR"
-		fi
-  fi
-
-	echo $1 >> "$LOG_TO"
 }
+
+#################################################################################
+# Set the log destination, copy existing logfile to new destination if it exists
+#################################################################################
 
 log_to() {
-  NEW_LOG=$1
-  if [ -n "$LOG_TO" ] ; then
-    cp "$LOG_TO" "$NEW_LOG"
+	NEW_LOG=$1
+
+	LOG_DIR=$(dirname $NEW_LOG)
+	if [ ! -d $LOG_DIR ] ; then
+		mkdir -p $LOG_DIR	|| fail  "failed to create log directory $LOG_DIR"
+	fi
+
+  if [ -n "$LOG_TO" ] && [ -f "$LOG_TO" ] ; then
+    cp "$LOG_TO" "$NEW_LOG" || fail  "failed to copy log file $LOG_TO to $NEW_LOG"
+	else
+		touch $NEW_LOG ||  fail  "failed to create log file $NEW_LOG"
   fi
+
   LOG_TO=$NEW_LOG
 }
+
+#################################################################################
+# log a regular message
+#################################################################################
 
 log() {
 	logMsg "LOG: $1"
 }
 
+debug() {
+	if [ -n "$DEBUG_STAGE2" ] ; then
+		logMsg "DEBUG: $1"
+  fi
+}
+
 term() {
 	logMsg "TERM: $1"
-	cat "$LOG_TO"
+
+	if [ -n "$LOG_TO" ] && [ -f "$LOG_TO" ] ; then
+		cat "$LOG_TO"
+  fi
+
 	if [ -n "$UMOUNT_LOG" ] ; then
 		umount $UMOUNT_LOG || true
 	fi
 
-  if [[ ! $FAIL_EXIT =~ ^\ *reboot ]] ; then
+	if [ `echo ${FAIL_EXIT} | grep -c reboot ` -eq 1 ] ; then
+		$FAIL_EXIT
+  else
 		if [ -n "$TERM_EXIT" ] ; then
 			$TERM_EXIT
 		else
-			$FAIL_EXIT $1
+			$FAIL_EXIT
 		fi
-  else
-		$FAIL_EXIT
 	fi
 }
 
 fail() {
 	logMsg "ERROR: $1"
-  if [[ ! "$FAIL_EXIT" =~ ^\ *reboot ]] ; then
-		log $1
+	logMsg "ERROR: terminating with $FAIL_EXIT"
+	if [ -n "$LOG_TO" ] && [ -f "$LOG_TO" ] ; then
 		cat "$LOG_TO"
+  fi
+
+	if [ -n "$UMOUNT_LOG" ] ; then
+		umount $UMOUNT_LOG || true
 	fi
+
+	# TODO: umount some more
 
 	$FAIL_EXIT
 }
