now loopmount flashed drive to save data

diff --git a/scripts/migrate-stage1 b/scripts/migrate-stage1
--- a/scripts/migrate-stage1
+++ b/scripts/migrate-stage1
@@ -69,35 +69,36 @@ fi
 
 inform "establishing required programs"
 
-CURL=$(command -v curl) || fail "could not find required command 'curl'"
-DD=$(command -v dd) || fail "missing command: dd"
-GREP=$(command -v grep) || fail "could not find required command 'grep'"
-LOSETUP=$(command -v losetup) || fail "could not find required command 'losetup'"
-MKDIR=$(command -v mkdir) || fail "missing command: mkdir"
-MKFSE4=$(command -v mkfs.ext4) || fail "could not find required command 'mkfs.ext4'"
-MKSWAP=$(command -v mkswap) || fail "could not find required command 'mkswap'"
-MOUNT=$(command -v mount) || fail "missing command: mount"
-PARTED=$(command -v parted) || fail "missing command: parted"
+CURL=$(which curl) || fail "could not find required command 'curl'"
+DD=$(which dd) || fail "missing command: dd"
+GREP=$(which grep) || fail "could not find required command 'grep'"
+LOSETUP=$(which losetup) || fail "could not find required command 'losetup'"
+MKDIR=$(which mkdir) || fail "missing command: mkdir"
+MKFSE4=$(which mkfs.ext4) || fail "could not find required command 'mkfs.ext4'"
+MKSWAP=$(which mkswap) || fail "could not find required command 'mkswap'"
+MOUNT=$(which mount) || fail "missing command: mount"
+PARTED=$(which parted) || fail "missing command: parted"
 PARTED_READ=${PARTED}
-RSYNC=$(command -v rsync) || fail "could not find required command 'rsync'"
-SED=$(command -v sed) || fail "could not find required command 'sed'"
-SWAPOFF=$(command -v swapoff) || fail "could not find required command 'swapoff'"
-SWAPON=$(command -v swapon) || fail "could not find required command 'swapon'"
+RSYNC=$(which rsync) || fail "could not find required command 'rsync'"
+SED=$(which sed) || fail "could not find required command 'sed'"
+SWAPOFF=$(which swapoff) || fail "could not find required command 'swapoff'"
+SWAPON=$(which swapon) || fail "could not find required command 'swapon'"
 SWAPSTAT=$SWAPON
-TUNE2FS=$(command -v tune2fs) || fail "could not find required command 'tune2fs'"
-UMOUNT=$(command -v umount) || fail "missing command: umount"
-GUNZIP=$(command -v gunzip) || fail "missing command: gunzip"
-GZIP=$(command -v gzip) || fail "missing command: gzip"
-FINDMNT=$(command -v findmnt) || fail "missing command: findmnt"
-LSBLK=$(command -v lsblk) || fail "missing command: lsblk"
-READLINK=$(command -v readlink) || fail "missing command: readlink"
-FSCK=$(command -v fsck) || fail "missing command: fsck"
-CHMOD=$(command -v chmod) || fail "missing command: chmod"
-
+TUNE2FS=$(which tune2fs) || fail "could not find required command 'tune2fs'"
+UMOUNT=$(which umount) || fail "missing command: umount"
+GUNZIP=$(which gunzip) || fail "missing command: gunzip"
+GZIP=$(which gzip) || fail "missing command: gzip"
+FINDMNT=$(which findmnt) || fail "missing command: findmnt"
+LSBLK=$(which lsblk) || fail "missing command: lsblk"
+READLINK=$(which readlink) || fail "missing command: readlink"
+FSCK=$(which fsck) || fail "missing command: fsck"
+CHMOD=$(which chmod) || fail "missing command: chmod"
+FDISK=$(which fdisk) || fail "missing command: fdisk"
+TAR=$(which tar) || fail "missing command: tar"
 # checkout grub
-GRUBUPDT=$(command -v update-grub) || fail "could not find required command 'update-grub'"
-GRUBREBOOT=$(command -v grub-reboot) || fail "could not find required command 'grub-reboot'"
-GRUBINST=$(command -v grub-install) || fail "could not find required command 'grub-install'"
+GRUBUPDT=$(which update-grub) || fail "could not find required command 'update-grub'"
+GRUBREBOOT=$(which grub-reboot) || fail "could not find required command 'grub-reboot'"
+GRUBINST=$(which grub-install) || fail "could not find required command 'grub-install'"
 GRUB_STR=$($GRUBINST -V)
 GRUB_VER=$(expr match "$GRUB_STR" '.*(GRUB).\([0-9]*\).*')
 if (( GRUB_VER < GRUB_MIN_VER )) ; then
@@ -697,6 +698,17 @@ EOT
     $GRUBREBOOT resin-migration
 }
 
+##########################################
+# getDiskId
+##########################################
+function getDiskId {
+    local disk=$1
+    local idLine=$(${FDISK} -l ${disk} | grep "Disk identifier:")
+    local id=$(expr match "${idLine}" 'Disk identifier: \(.*\)')
+    echo ${id}
+}
+
+
 
 
 ##########################################
@@ -724,20 +736,34 @@ function setupMigration {
 
     # save information for stage 2
 
+    # TODO: need to find a new way to identify drives
+    # eg. enumerrate them like grub does
+
     inform "creating migrate-stage2.conf"
 
-    $MOUNT "${SWAP_DEV}${SWAP_PART_PAD}${FLASH_ROOTA_PART_NO}" ${MOUNT_DIR1} || fail "failed to mount ${SWAP_DEV}${SWAP_PART_PAD}${FLASH_BOOT_PART_NO} as ${MOUNT_DIR1}"
+    $MOUNT "${SWAP_DEV}${SWAP_PART_PAD}${FLASH_ROOTA_PART_NO}" ${MOUNT_DIR1} || fail "failed to mount ${SWAP_DEV}${SWAP_PART_PAD}${FLASH_ROOTA_PART_NO} as ${MOUNT_DIR1}"
     inform "writing migrate conf to ${MOUNT_DIR1}/etc/migrate-stage2.conf"
     echo "#!/bin/sh " > ${MOUNT_DIR1}/etc/migrate-stage2.conf || fail "failed to write migrate-stage2.conf"
-    echo "ORIG_BOOT_DEV=${ORIG_ROOT_DEV}" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
-    echo "ORIG_ROOT_PART=${ORIG_ROOT_PART}" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
+    # echo "ORIG_BOOT_DEV=${ORIG_ROOT_DEV}" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
+    echo "ORIG_BOOT_DEV_ID=$(getDiskId ${ORIG_ROOT_DEV})" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
+    echo "ORIG_ROOT_PART_NO=${ORIG_ROOT_PART_NO}" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
+    echo "FLASH_DATA_PART_NO=${FLASH_DATA_PART_NO}" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
     # somehow flash-data label does not show up in stage 2
-    echo "FLASH_DATA_PART=${FLASH_DATA_PART}" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
     # TODO: add links to customer provided delete & backup files here
-    echo "CUSTOMER_BACKUP_SCRIPT=" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
-    echo "CUSTOMER_DELETE_SCRIPT=" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
+    # echo "CUSTOMER_BACKUP_SCRIPT=" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
+    # echo "CUSTOMER_DELETE_SCRIPT=" >> ${MOUNT_DIR1}/etc/migrate-stage2.conf
+
+    cat ${MOUNT_DIR1}/etc/migrate-stage2.conf
 
     $CHMOD +x ${MOUNT_DIR1}/etc/migrate-stage2.conf
+
+    $UMOUNT ${MOUNT_DIR1}
+
+
+
+    # TODO: create backup here
+    $MOUNT "${SWAP_DEV}${SWAP_PART_PAD}${FLASH_DATA_PART_NO}" ${MOUNT_DIR1} || fail "failed to mount ${SWAP_DEV}${SWAP_PART_PAD}${FLASH_DATA_PART_NO} as ${MOUNT_DIR1}"
+    $TAR -czf ${MOUNT_DIR1}/backup_etc.tgz /etc/* || fail "failed to save backup on flasher-data"
     $UMOUNT ${MOUNT_DIR1}
 
     setupGrub ${SWAP_DEV} ${FLASH_BOOT_PART_NO}
@@ -760,7 +786,7 @@ function setupMigration {
 if [ -z ${FLASH_IMG_GEOMETRY_FILE} ] ; then
     fail "FLASH_IMG_GEOMETRY_FILE is not defined"
 else
-    if [! -f ${FLASH_IMG_GEOMETRY_FILE} ] ; then
+    if [ ! -f ${FLASH_IMG_GEOMETRY_FILE} ] ; then
         fail "config file not found: ${FLASH_IMG_GEOMETRY_FILE}"
     fi
 fi
diff --git a/scripts/migrate-stage2 b/scripts/migrate-stage2
--- a/scripts/migrate-stage2
+++ b/scripts/migrate-stage2
@@ -126,6 +126,36 @@ function getPartStartOffset {
     done < <(parted -ms ${hdDev} unit s print) || fail "failed to read ${hdDev} image partitions"
 }
 
+function getDeviceName {
+    local devId=$1
+
+    # Disk /dev/hda: 8 GiB, 8589934592 bytes, 16777216 sectors
+    # Units: sectors of 1 * 512 = 512 bytes
+    # Sector size (logical/physical): 512 bytes / 512 bytes
+    # I/O size (minimum/optimal): 512 bytes / 512 bytes
+    # Disklabel type: dos
+    # Disk identifier: 0x000f073d
+
+
+    while read line ;
+    do
+        if [[ $line =~ ^Disk\ identifier:\ .*$ ]] ; then
+             local diskId=$(expr match "${line}" 'Disk identifier: \(.\+\)')
+             # inform "found id ${diskId} for ${diskName}"
+             if [ "${devId}" == "${diskId}" ] ; then
+                echo ${diskName}
+                break
+             fi
+        else
+            if [[ ${line} =~ ^Disk\ .+$ ]] ; then
+                 local diskName=$(expr match "${line}" 'Disk \([^:]\+\):.*')
+                 # inform "looking at ${diskName}"
+                 continue
+            fi
+        fi
+    done < <(fdisk -l) || fail "failed to enumerate drives"
+}
+
 
 ########
 # MAIN #
@@ -136,15 +166,26 @@ if [ "$EUID" -ne 0 ]; then
     fail "Please run as root."
 fi
 
+# fail "dummy - not doing anything"
 
-inform "Board specific initialization..."
-/usr/bin/resin-init-board
+# TODO: if resin-init-board has to be run it needs to be adapted to use loop mounted image
+# inform "Board specific initialization..."
+# /usr/bin/resin-init-board
 
 if [ -f ${MIGRATE_CONF_FILE} ] ; then
     source ${MIGRATE_CONF_FILE} || fail "failed to read migrate config file"
 else
     fail "No migration configuration for resin-init-flasher."
 fi
+
+
+ORIG_BOOT_DEV=$(getDeviceName ${ORIG_BOOT_DEV_ID})
+
+if [ -z "${ORIG_BOOT_DEV}" ] || [ ! -b ${ORIG_BOOT_DEV} ] ; then
+    fail "could not identify boot device"
+fi
+
+inform "using device ${ORIG_BOOT_DEV}"
 
 # Configuration file
 if [ -f $FLASHER_CONF_FILE ]; then
@@ -169,34 +210,35 @@ fi
 
 ## TODO: prepare and loopmount resinOS boot partition
 
-inform "mounting original root dir"
-mkdir -p ${ORIG_ROOT_MOUNTPOINT}
-if [ -d ${ORIG_ROOT_MOUNTPOINT} ] ; then
-    inform "attempting mount ${ORIG_ROOT_PART} ${ORIG_ROOT_MOUNTPOINT}"
-    mount ${ORIG_ROOT_PART} ${ORIG_ROOT_MOUNTPOINT}
-    DISK_FREE=$(getSpaceInFs ${ORIG_ROOT_MOUNTPOINT})
-    if (( $DISK_FREE < ORIG_ROOT_REQ_SPACE )) ; then
-        if [ ! -z "${CUSTOMER_DELETE_SCRIPT}" ]  &&  [ -f "${CUSTOMER_DELETE_SCRIPT}" ] ; then
-            # TODO: really ?
-            ${CUSTOMER_DELETE_SCRIPT} || fail "customer provided delete script failed"
-        fi
-    fi
-
-    DISK_FREE=$(getSpaceInFs ${ORIG_ROOT_MOUNTPOINT})
-    if (( $DISK_FREE < $ORIG_ROOT_REQ_SPACE )) ; then
-        fail "not enough space on device to unpack resinOS image"
-    fi
-
-    mkdir -p ${ORIG_ROOT_MOUNTPOINT}/tmp
-    inform "gunzip /opt/${RESIN_IMAGE}.gz, please wait.."
-    gunzip -c "/opt/${RESIN_IMAGE}.gz" > ${ORIG_ROOT_MOUNTPOINT}/${RESIN_IMAGE} || fail "failed to gunzip resinOS image to ${ORIG_ROOT_MOUNTPOINT}/${RESIN_IMAGE}"
-    BOOT_START=$(getPartStartOffset "${ORIG_ROOT_MOUNTPOINT}/${RESIN_IMAGE}" 1 )
-    mkdir -p ${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}
-    inform "attempting mount -o loop,offset=${BOOT_START} ${ORIG_ROOT_MOUNTPOINT}/${RESIN_IMAGE} ${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT} "
-    mount -o loop,offset=${BOOT_START} ${ORIG_ROOT_MOUNTPOINT}/${RESIN_IMAGE} ${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT} || fail "Failed to loop-mount resin-boot on ${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}"
+FLASH_BOOTLOADER=
+# Stuff from resin-init-flasher-board
+if efibootmgr &>/dev/null ; then
+    INSTALL_UEFI="TRUE"
 else
-    fail "failed to create mountpoint for orig boot in ${ORIG_ROOT_MOUNTPOINT}"
+    FLASH_BOOTLOADER="TRUE"
 fi
+
+# need to mount this now, won't work any more after flashing
+mkdir -p ${FLASH_DATA_MOUNTPOINT}
+mount ${ORIG_BOOT_DEV}9 ${FLASH_DATA_MOUNTPOINT} || fail "failed to mount flash-data"
+
+
+inform "flashing resinOS image to ${ORIG_BOOT_DEV}"
+gunzip -c /opt/${RESIN_IMAGE}.gz | dd of=${ORIG_BOOT_DEV} bs=4M || fail "failed to flash resinOS image to ${ORIG_BOOT_DEV}"
+
+if [ "${FLASH_BOOTLOADER}" == "TRUE" ] ; then
+    inform "flashing boot.img os to ${ORIG_BOOT_DEV}"
+    dd if=${BOOT_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1
+    inform "flashing core.img os to ${ORIG_BOOT_DEV}"
+    dd if=${CORE_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1 seek=512
+fi
+
+sync
+
+BOOT_START=$(getPartStartOffset  ${ORIG_BOOT_DEV} 1)
+inform "boot part start offset: ${BOOT_START}"
+mkdir -p "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT"
+mount -o loop,offset=${BOOT_START} ${ORIG_BOOT_DEV} ${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT} || fail "failed to mount new boot partition"
 
 # Copy custom splash dir
 mkdir -p "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$SPLASH_DIRNAME"
@@ -220,15 +262,25 @@ else
     inform "No proxy configuration found to transfer on the internal device."
 fi
 # Copy bootloader config file
+
 if [ -n "${INTERNAL_DEVICE_BOOTLOADER_CONFIG}" ] && [ -f "${EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}/${INTERNAL_DEVICE_BOOTLOADER_CONFIG}" ]; then
         if [[ -z "${INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH}" ]]; then
             fail "INTERNAL_DEVICE_BOOTLOADER_CONFIG needs INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH to be set."
         fi
+
         cp "$EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH"
 
         if [ -n "${INTERNAL_DEVICE_BOOTLOADER_LEGACY_CONFIG_PATH}" ]; then
             cp "$EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_CONFIG" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$INTERNAL_DEVICE_BOOTLOADER_LEGACY_CONFIG_PATH"
         fi
+fi
+
+if [ -z $INSTALL_UEFI ]; then
+    inform "non-UEFI installation."
+    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/EFI"
+else
+    inform "UEFI installation."
+    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/grub"
 fi
 
 # Copy resinOS bootloader config file
@@ -253,57 +305,19 @@ done
 # Copy json configuration file from external (flasher) to the internal (booting) device
 cp -rvf "$CONFIG_PATH" "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT"
 
-FLASH_BOOTLOADER=
-# Stuff from resin-init-flasher-board
-if efibootmgr &>/dev/null ; then
-    INSTALL_UEFI="TRUE"
-fi
-if [ -z $INSTALL_UEFI ]; then
-    echo "[resin-init-flasher-board] non-UEFI installation."
-    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/EFI"
-    FLASH_BOOTLOADER="TRUE"
-else
-    echo "[resin-init-flasher-board] UEFI installation."
-    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/grub"
-fi
-
+sync
 umount ${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}
+
+
+DATA_START=$(getPartStartOffset  ${ORIG_BOOT_DEV} 6)
+inform "resin-data part start offset: ${BOOT_START}"
+mkdir -p "${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT}"
+mount -o loop,offset=${DATA_START} ${ORIG_BOOT_DEV} ${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT} || fail "failed to mount resin-data partition"
+
+cp -rax ${FLASH_DATA_MOUNTPOINT}/backup* ${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT}/
 sync
-
-
-if [ ! -z "$CUSTOMER_BACKUP_SCRIPT" ]  && [ -f "$CUSTOMER_BACKUP_SCRIPT" ] ; then
-    inform "mounting resin-data for device backup"
-    mkdir -p ${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT}
-    DATA_START=$(getPartStartOffset "${ORIG_ROOT_MOUNTPOINT}/${RESIN_IMAGE}" 6 )
-    mount -o loop,offset=${DATA_START} ${ORIG_ROOT_MOUNTPOINT}/${RESIN_IMAGE} ${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT} || fail "Failed to loop-mount resin-data on ${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT}"
-    inform "calling backup script"
-    ${CUSTOMER_BACKUP_SCRIPT}  ${ORIG_ROOT_MOUNTPOINT} ${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT} || fail "customer backup script failed"
-    # TODO: sync & unmount resinOS data
-    sync
-    umount ${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT}
-fi
-
-mkdir -p ${FLASH_DATA_MOUNTPOINT}
-mount ${FLASH_DATA_PART} ${FLASH_DATA_MOUNTPOINT} || fail "failed to mount flash-data"
-gzip -c ${ORIG_ROOT_MOUNTPOINT}/${RESIN_IMAGE} > ${FLASH_DATA_MOUNTPOINT}/tmp.img || fail "failed to rezip resinOS image to ${FLASH_DATA_MOUNTPOINT}/tmp.img"
-
-inform "flashing resin os to ${ORIG_BOOT_DEV}"
-gunzip -c ${FLASH_DATA_MOUNTPOINT}/tmp.img | dd of=${ORIG_BOOT_DEV} bs=4M
-# rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/EFI"
-
-if [ "${FLASH_BOOTLOADER}" == "TRUE" ] ; then
-    inform "flashing boot.img os to ${ORIG_BOOT_DEV}"
-    dd if=${BOOT_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1
-    inform "flashing core.img os to ${ORIG_BOOT_DEV}"
-    dd if=${CORE_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1 seek=512
-fi
-
-if [ "$INSTALL_UEFI" == "TRUE" ] ; then
-    echo "Add UEFI boot entry for starting resinOS from internal media."
-    efibootmgr -c -d ${ORIG_BOOT_DEV} -p 1 -L "resinOS" -l "\EFI\BOOT\bootx64.efi"
-fi
-
-sync
+umount ${FLASH_DATA_MOUNTPOINT}
+umount ${INTERNAL_DEVICE_DATA_PART_MOUNTPOINT}
 
 inform "rebooting device ..."
 reboot
